# -*- coding: utf-8 -*-
# קובץ הגדרות קטגוריות באנגלית ועברית
# ניתן לייבא: from channel_keywords import CATEGORY_KEYWORDS_EN, CATEGORY_KEYWORDS_HE

CATEGORY_KEYWORDS_EN = {
    # ========================
    # קיימות - חדשות ישראל
    # ========================
    'News📺': [
        # מקורי נשמר והורחב, ללא כל מופע שקשור לערבית
        'Keshet 12 IL', 'Channel 9 HD IL', '9 Channel IL', 'CHANNEL 9 HD IL', 'KAN 11 IL', '12 Keshet IL',
        'C13 Keshet IL', 'KAN 14 IL', 'Channel 9 IL', 'Kan 11 IL', 'Knesset Channel IL','Keshet HD', 'Channel 9 HD', 'Channel 9 HD',
        'i24 IL', 'Channel 14', 'Kan Educational HD IL', 'Reshet 13 IL', 'KHAN 11', 'CBS reality [IL]',
        'Channel 9 HD', 'Channel 11', 'Channel 12', 'Channel 13', 'Reshet 13 [IL]', 'Knesset [IL]',
        'I24 News [IL]', 'Keshet 12 HD [IL]', 'Keshet 12 [IL]', 'Reshet 13 HD [IL]', '13 Keshet IL',
        'KAN 11 HD [IL]', 'KAN 11 [IL]', 'Kan Chinuchit 23', 'i24 News', 'Channel 9','24 IL',
        'Now 14 HD [IL]', 'KAN23 [IL]', 'Kan Educational HD [IL]','Mekan IL',
        'Channel 24', 'Channel 98 IL', 'CHANNEL 12 HD IL', 'CHANNEL 13 HD',
        'Kan 11 HD IL', 'Kan Educational IL', 'Keshet 12 FHD IL', 'Keshet 12 HD IL', 'Reshet 13 HD IL',
        'IL: Israel HD', 'IL: Kneest', 'IL: Kabbalah TV', 'IL: Kalkala 10 HD',
        'IL: Channel 9 4K', 'IL: Channel 9 FHD', 'IL: Channel 9', 'IL: Channel 12 4K', 'IL: Channel 12 FHD',
        'IL: Channel 12 HD', 'IL: Channel 12 SD', 'IL: Channel 13 4K', 'IL: Channel 13 FHD', 'IL: Channel 13 HD',
        'IL: Channel 13 SD', 'IL: Channel 14 4K', 'IL: Channel 14 HD', 'IL: Channel 24 4K', 'IL: Channel 24 FHD',
        'IL: Channel 24', 'ID', 'Knesset', 'Knesset FHD',
        'כאן 11', 'כאן11', 'כאן 11 HD', 'כאן חינוכית', 'כאן 23', 'ערוץ 11',
        'קשת 12', 'קשת12', 'חדשות 12', 'חדשות12', 'הכל כלול 13', 'רשת 13', 'רשת13', 'חדשות 13', 'חדשות13',
        'ערוץ 14', 'עכשיו 14', 'Now 14', 'ערוץ 24', 'מיוזיק 24', 'מוזיקה 24',
        'ערוץ הכנסת', 'כנסת', 'קבלה טי וי', 'כלכלה 10', 'ערוץ 9', 'ישראל פלוס', 'ישראל פלוס אינטרנשיונל',
        'i24NEWS', 'i24', 'כאן חדשות'
    ],

    # ========================
    # קיימות - HOT
    # ========================
    'Hot🔥': [
        'HOT', 'HOT CINEMA', 'HOT Cinema 1 HD IL', 'HOT CINEMA 1', 'HOT CINEMA 3', 'HOT CINEMA 4', 'HOT3 HD',
        'HOT 8 HD', 'Hot HBO', 'HOT cinema 1', 'HOT cinema 2', 'HOT cinema 3', 'HOT COMEDY CENTRAL', 'hot-IL', 'HoT',
        'IL: HOT Zero One 1', 'IL: HOT Zero One 2', 'IL: HOT 3 HD', 'IL: HOT 8 HD', 'IL: HOT Cinema Family FHD', 'IL: HOT ZONE HD',
        'IL: HOT HBO FHD', 'IL: HOT HBO HD', 'IL: HOT Cinema 1', 'IL: HOT Cinema 1 HD', 'IL: HOT Cinema 1 FHD', 'IL: HOT Cinema 2',
        'IL: HOT Cinema 2 HD', 'IL: HOT Cinema 2 FHD', 'IL: HOT Cinema 3', 'IL: HOT Cinema 3 HD', 'IL: HOT Cinema 3 FHD',
        'IL: HOT Cinema 4', 'IL: HOT Cinema 4 HD', 'IL: HOT Cinema 4 FHD', 'IL: HOT Comedy Central HD', 'IL: HOT Bidur',
        'IL: HOT Bollywood HD', 'IL: HOT Bollyshow', 'IL: HOT Design', 'IL: HOT Kidz', 'IL: HOT Nofesh', 'IL: HOT Reality',
        'IL: HOT Style', 'IL: HOT Turkish Drama 1', 'IL: HOT Turkish Drama 2', 'IL: HOT Turkish Drama 3', 'IL: HOT Vamos',
        'IL: HOT Viva Premium', 'IL: HOT Viva Vintage', 'IL: HOT Yam Tichoni', 'IL: HOT Yam Tichoni plus', 'IL: HOT Zoom Toom',
        'הוט 3', 'הוט 8', 'הוט זון', 'הוט בידור', 'הוט בידור ישראלי', 'קומדי סנטרל', 'HOT קומדי סנטרל',
        'הוט קידז', 'הוט סטייל', 'HOT עיצוב', 'הוט נופש', 'HOT נופש', 'HOT בוליווד', 'HOT סרטים 1', 'HOT סרטים 2', 'HOT סרטים 3', 'HOT סרטים 4'
    ],

    # ========================
    # קיימות - Yes
    # ========================
    'Yes👑': [
        'yes', 'Yes', 'YES', 'Yes_IL', 'YES_IL', 'yes Israeli Cinema HD', 'Yes E', 'Yes TV Drama HD', 'Sport-IL', 'YES HD IL', 'YES TV', 'yes tv',
        'IL: Yes Wiz', 'IL: YES SPORT 1 ToGo FHD', 'IL: YES SPORT 2 ToGo FHD', 'IL: YES SPORT 1 FHD', 'IL: YES SPORT 1 HD',
        'IL: YES SPORT 2 FHD', 'IL: YES SPORT 2 HD', 'IL: YES SPORT 3 FHD', 'IL: YES SPORT 3 HD', 'IL: YES SPORT 4 FHD', 'IL: YES SPORT 4 HD',
        'IL: YES+ Diamonds FHD', 'IL: YES+ Cinema FHD', 'IL: YES TV Action FHD', 'IL: YES TV Action HD [Multi-Sub]', 'IL: YES TV Action HD',
        'IL: YES TV Comedy FHD', 'IL: YES TV Comedy HD [Multi-Sub]', 'IL: YES TV Comedy HD', 'IL: YES TV Drama FHD', 'IL: YES TV Drama HD [Multi-Sub]',
        'IL: YES TV Drama HD', 'IL: YES TV Kids FHD', 'IL: YES TV Kids HD [Multi-Sub]', 'IL: YES TV Kids HD', 'IL: YES Movies Action FHD',
        'IL: YES Movies Action HD [Multi-Sub]', 'IL: YES Movies Action HD', 'IL: YES Movies Kids FHD', 'IL: YES Movies Kids HD [Multi-Sub]',
        'IL: YES Movies Drama FHD', 'IL: YES Movies Drama HD [Multi-Sub]', 'IL: YES Movies Drama HD', 'IL: YES Movies Comedy FHD',
        'IL: YES Movies Comedy HD [Multi-Sub]', 'IL: YES Movies Comedy HD', 'IL: YES Docu FHD', 'IL: YES Docu HD [Multi-Sub]', 'IL: YES Docu HD',
        'IL: YES Cinema HD [Multi-Sub]', 'IL: YES Cinema HD',
        'יס', 'יס דוקו', 'יס קומדי', 'יס דרמה', 'יס אקשן', 'יס קידס', 'יס ילדים', 'יס סרטים', 'יס מוביז', 'יס סינמה',
        'yes Action', 'yes Comedy', 'yes Drama', 'yes Docu', 'yes Kids', 'yes Movies', 'yes Cinema', 'yes Oh',
        'יס או', 'יס או או', 'יס פלוס', 'Yes+', 'יס ויז', 'Yes Wiz', 'יש טיוי', 'יס טיוי'
    ],

    # ========================
    # קיימות - Partner
    # ========================
    'Partner🌈': [
        'Partner Yladim', 'Partner Sratim', 'Partner Sdarot',
        'IL: Kan11 HD', 'IL: Partner TV Comedy', 'IL: Partner TV Kids', 'IL: Partner TV Movies', 'IL: Partner TV Netflix', 'IL: Partner TV Series',

        # תוספות בעברית
        'פרטנר TV', 'פרטנר טיוי', 'פרטנר קומדי', 'פרטנר ילדים', 'פרטנר סרטים', 'פרטנר סדרות', 'Partner TV'
    ],

    # ========================
    # קיימות - Cellcom
    # ========================
    'Cellcom🐶': [
        'Cellcom Israel', 'Cellcom Rus', 'IL: Cellcom TV Family', 'IL: Cellcom TV HBO', 'IL: Cellcom TV Isreal',
        'Cellcom Sratim', 'Cellcom Yeladim', 'Cellcom HBO HD', 'Cellcom Doco HD',
        'IL: Cellcom TV Kids', 'IL: Cellcom TV Movies', 'IL: Cellcom TV Now', 'IL: Cellcom TV Yvin',
        'סלקום TV', 'סלקום טיוי', 'סלקום משפחה', 'סלקום סרטים', 'סלקום ילדים', 'סלקום דוקו', 'סלקום HBO'
    ],

    # ========================
    # קיימות - Free TV
    # ========================
    'Free Tv🌞': [
        'Free Tv Drama HD', 'Free Tv Comedy HD', 'Free Tv Lifestyle HD', 'Free Israeli Movies HD',
        'Free Movies Family HD', 'Free Movies Horror HD', 'Free Movies Romantic HD', 'Free Movies Comedy HD','Free TV Kohav Haba IL',
        'Free Movies Drama HD', 'Free Series Global HD', 'Free Movies Action HD', 'Free Tv Cooking HD','Free TV Karaoke IL', 'Free TV Karaoke',
        'Free Tv Doco HD', 'Free Tv Hatuna HD', 'Free Tv Karaoke HD', 'Free Tv Kohav Haba HD', 'Free Tv Feel Good','Free Movies Comedy IL', 'Free Movies',
        'IL: Free Movies 10 Stars HD','Free Series Global IL', 'Free Series', 'Free Tv Cooking IL', 'Free Tv Doco', 'Free Tv Karaoke', 'Free Tv Kohav', 'Free Tv Feel'
        'IL: FreeTV Asuta Doc FHD', 'IL: FreeTV Series Global FHD', 'IL: FreeTV Israeli Movies FHD', 'IL: FreeTV Series','Free Series Global IL', 'Free Series',
        'IL: FreeTV Movies 10 Stars FHD', 'IL: FreeTV Movies Action FHD', 'IL: FreeTV Movies Comedy FHD','Free Movies Horror IL','Free Movies Horror IL',
        'IL: FreeTV Movies Drama FHD', 'IL: FreeTV Movies Romance FHD', 'IL: FreeTV Imagin Comedy FHD','Free Movies Romantic IL','Free Movies Action IL','Free Movies Action IL',
        'IL: FreeTV Imagin Cooking FHD', 'IL: FreeTV Imagin Doco FHD', 'IL: FreeTV Imagin Drama FHD','Free Israeli Movies IL','Free TV Hatuna IL',
        'IL: FreeTV Imagin lifestyle FHD', 'IL: FreeTV Movies Family FHD', 'IL: FreeTV Movies Horror FHD',
        'FreeTV', 'פרי טיוי', 'ערוצי חינם', 'ערוצי פרי', 'חינמי', 'ערוצי סטרים חינם'
    ],

    # ========================
    # קיימות - ספורט
    # ========================
    'Sports🏀': [
        'Sport 1', 'Sport 2', 'Sport 3', 'Sport 4', 'Sport 5', 'Sport-IL', 'Sport_il', 'Sport', 'ONE ',
        'ONE HD', 'Eurosport 2', 'Sport 1 HD', 'EXTREME IL', 'Sport 5+ Live HD IL', 'ONE 2 HD IL', 'Sport 3 HD IL',
        'Sport 5 HD IL ', 'SPORT 2 HD IL', 'Sport 1 HD IL', 'Sport 2 HD', 'Sport 3 HD', 'Sport 4 HD', '5 Live IL', 'ONE1 HD IL',
        'ONE2 HD IL', 'ONE2 HD [IL]', 'ONE2  [IL]', 'Sport 5 HD', 'Sport 5 Live HD', 'Eurosport 1 HD', 'ESPN 2 HD USA', 'ESPN USA',
        'Red Bull TV HD', 'WWE Russian', 'Red Bull TV', 'MMA-TV.com HD', 'NHL', 'nba', 'NBA', 'wwe', 'WWE Network HD', 'MMA-TV.com',
        'MMA-TV.com orig', 'EXTREME', 'SPORT',
        'IL: ONE 1 4K', 'IL: ONE 1 FHD P50', 'IL: ONE 1 FHD', 'IL: ONE 1 HD', 'IL: ONE 2 4K', 'IL: ONE 2 FHD P50', 'IL: ONE 2 FHD',
        'IL: ONE 2 HD', 'IL: ONE DOCO FHD', 'IL: ONE EDGE FHD', 'IL: Sport 5 4K', 'IL: Sport 5+ UHD 4K', 'IL: Sport 5+ 4K',
        'IL: Sport 5 FHD P50', 'IL: Sport 5 FHD', 'IL: Sport 5 HD', 'IL: Sport 5 SD', 'IL: Sport 5+ Live 4K',
        'IL: Sport 5+ Live FHD P50', 'IL: Sport 5+ Live FHD', 'IL: Sport 5+ Live HD', 'IL: Sport 5+ Stars 4K',
        'IL: Sport 5+ Stars FHD P50', 'IL: Sport 5+ Stars FHD', 'IL: Sport 5+ Stars HD', 'IL: Sport 5+ Plus 4K',
        'IL: Sport 5 Plus FHD', 'IL: Sport 5 Plus', 'IL: Sport 5+ Gold 4K', 'IL: Sport 5 Gold', 'IL: Fox Sport HD',
        'IL: Eurosport 1 HD', 'IL: Eurosport 2 HD', 'IL: Extreme Sports', 'IL: Trace Spôrt Stars',
        'ספורט 1', 'ספורט1', 'ספורט 2', 'ספורט2', 'ספורט 3', 'ספורט3', 'ספורט 4', 'ספורט4', 'ספורט 5', 'ספורט5',
        'ערוץ הספורט', 'חמש פלוס', '5 פלוס', 'חמש פלוס לייב', '5 פלוס לייב', 'חמש לייב', 'חמש גולד', '5 גולד',
        'חמש סטארס', '5 סטארס', 'ONE 1', 'ONE1', 'ONE 2', 'ONE2', 'יורוספורט 1', 'יורוספורט 2', 'ערוץ האקסטרים',
        'Edge', 'DOCO Sports'
    ],

    # ========================
    # קיימות - ילדים
    # ========================
    'Kids🍦': [
        'BABY TV IL', 'Baby', 'Baby IL', 'Baby TV', 'DISNEY CHANNEL', 'DISNEY JR IL',
        'Disney Channel H', 'Disney HD', 'Disney Jr IL', 'Disney Jr [IL]', 'Disney Jr.', 'Disney Junior',
        'Disney [IL]', 'FOMO [IL]', 'HOP CHILDHOOD IL', 'HOP HD IL', 'HOP [IL]', 'HOT A+ Kids',
        'Hop Israeli Childhood', 'Hop Pele HD', 'Hop!', 'Hop! Childhood', 'Israelit', 'JUNIOR IL',
        'Jim Jam', 'Junior', 'Junior IL', 'KIDS HD IL', 'LULI IL', 'Logi', 'Luli', 'NICK HD IL',
        'NICK JR HD IL', 'Nick HD', 'Nick Jr', 'Nick Jr HD', 'Nick Jr IL', 'Nickelodeon',
        'TeenNick', 'TeenNick IL', 'WIZ IL', 'Wiz', 'Yaldut', 'Yaldut IL', 'Yalduti','Aruch Hayeladim IL',
        'YoYo', 'Yoyo [IL]', 'ZOOM', 'ZOOM IL', 'Zoom', 'Zoom Toon HD', 'hop', 'hop IL',
        'Baby TV [UK]', 'Baby [IL]', 'Hop', 'IL: A+ kids', 'Junior [IL]', 'Kids IL',
        'Luli [IL]', 'Nick Jr [IL]', 'Nickelodeon [IL]', 'TeenNick [IL]', 'ZOOM TOON [IL]',
        'ZOOM [IL]',
        'IL: Zoom', 'IL: A+ Kids', 'IL: Baby FHD', 'IL: HOP Pele FHD', 'IL: Junior FHD',
        'IL: logi FHD', 'IL: Logi', 'IL: Yalduti FHD', 'IL: Yalduti HD', 'IL: Yalduti Songs FHD',
        'IL: YOYO FHD', 'IL: HOP', 'IL: HOP YALDUT', 'IL: Disney HD', 'IL: Nickelodeon',
        'IL: Nick Jr', 'IL: Baby TV', 'IL: Luli', 'IL: Junior', 'IL: Israel Shopping Channel',
        'IL: Kids Channel FHD', 'IL: Disney Jr', 'IL: NickTeen', 'IL: JLTV HD', 'IL: DIY Channel FHD',
        'ערוץ הילדים', 'ניקלודיאון', 'ניק', 'ניק גוניור', 'טין ניק', 'דיסני', 'דיסני גוניור', 'דיסני קידס',
        'הופ', 'הופ ילדות ישראלית', 'הופ הורים', 'לוגי', 'לולי', 'יויו', 'זום', 'זום טון'
    ],

    # ========================
    # קיימות - בידור
    # ========================
    'Entertainment🧸': [
        '5Stars HD IL', 'A+ HD IL', 'Arutz Haofna Haisraeli HD IL',
        'Boomerang', 'CANAL+ FAMILY HD PL', 'CBS Reality', 'E!', 'E! [IL]', 'E! IL',
        'EGO TOTAL HD IL', 'Ego Total', 'Ego Total [IL]', 'Entertainment IL', 'Erez Nehederet HD',
        'Fashion', 'Fashion TV', 'Foody HD', 'Foody HD [IL]', 'Food Channel', 'Food Channel HD','World Action IL', 'World Action','World Action 2 IL',
        'FOOD CHANNE IL', 'Fomo', 'Game Show Channel HD IL', 'Good Life', 'Good Life [IL]', 'Health',
        'Health channel [IL]', 'HEALTH CHANNEL', 'HISTORY HD IL', 'History HD', 'Holiday channel [IL]',
        'Home Plus', 'Home Plus IL', 'Horse and Country TV', 'HUMOR CHANNEL', 'Humor Channel',
        'Humor Channel HD [IL]', 'IL: Extreme', 'IL: Humor Chanenel', 'IL: Stars', 'Israeli Fashion [IL]',
        'LIFETIME HD IL', 'Love Island', 'Polsat HD', 'Reality HD', 'RedBull TV [UK]', 'Savri HD','Humor IL','Reality IL', 'Reality HD',
        'Star Channel', 'Star channel [IL]', 'STARS HD IL', 'STARS IL', 'The Food Channel [IL]','Imagin Comedy IL', 'Imagin Comedy',
        'TLC HD', 'ZONE HD','HBO IL', 'ZONE HD', 'ZONE', 'Doco IL', 'Erez Nehederet IL', 'Erez Nehederet','Savri IL'
        'IL: A Plus FHD', 'IL: BBC entertainement', 'IL: Big Brother 26', 'IL: Big Brother 26 FHD','Big Brother IL',
        'IL: CBS Reality', 'IL: Classic FHD', 'IL: E! Entertainment', 'IL: Ego Total', 'IL: Erez Nehederet FHD','Imagin Lifestyle IL','Imagin Cooking IL',
        'IL: Fashion Isreal HD', 'IL: Fomo FHD', 'IL: Food Channel', 'IL: Food Network HD', 'IL: Fox Business HD','Imagin Doco IL'
        'IL: Game Show', 'IL: GoodLife', 'IL: GTV', 'IL: Hatunami POPUP FHD', 'IL: Health Channel',
        'IL: History', 'IL: Holiday channel', 'IL: Home Plus', 'IL: Horse and Country TV', 'IL: Humor Channel',
        'IL: Israeli Fashion', 'IL: Lifetime', 'IL: Me TV', 'IL: National Geo Wild', 'IL: National Geo Wild HD',
        'IL: National Geographic', 'IL: National Geographic HD', 'IL: Next Star POPUP FHD','History IL', 'History IL', 'History',
        'IL: Ninja POPUP FHD', 'IL: Reality HD', 'IL: Savri FHD', 'IL: Starz FHD', 'IL: The Humor Channel','TLC IL', 'TLC National Geo Wild',
        'IL: TLC', 'IL: Together HD', 'IL: Travel HD',
        'ערוץ האוכל', 'פודי', 'פוד נייטוורק', 'החיים הטובים', 'ערוץ הבריאות', 'ערוץ האופנה', 'ערוץ ההיסטוריה',
        'ערוץ ההומור', 'תעלומות', 'ריאליטי', 'האח הגדול', 'נינגה ישראל', 'הכוכב הבא'
    ],

    # ========================
    # קיימות - מוזיקה
    # ========================
    'Music🎵': [
        '1HD Music Television orig', '4ever Music HD UA', '4ever Music UA', 'B4U Music IN', 'Backus TV Music HD',
        'Baraza Music HD', 'Biz Music HD UZ', 'BOX Music 4K HDR', 'BRIDGE TV Deluxe', 'BRIDGE TV HITS',
        'BRIDGE TV Русский Хит', 'Bridge Deluxe HD', 'Bridge Deluxe HD orig', 'Bridge Hits', 'Bridge Rock',
        'Bridge TV', 'Bridge TV Classic', 'Bridge TV ROCK', 'C Music TV', 'CHANNEL 24 MUSIC HD IL',
        'Classic Music', 'Classic Music HD', 'Clarity4K Bollywood music', 'Clarity4K France music',
        'Clarity4K Korean music', 'Clarity4K Latin music', 'Clarity4K Remastered music',
        'Clarity4K Russian music', 'Club MTV', 'Clubbing TV HD',
        'Disco Polo Music PL', 'EU Music HD UA', 'EU Music UA', 'Europa Plus TV', 'Europa Plus TV HD',
        'Europa Plus TV orig', 'FRESH Sad Music HD', 'Fresh Concerts', 'Fresh Dance', 'HIT MUSIC [RO]',
        'HMTV IN', 'IL: MTV HD', 'IT: MTV HD', 'ITV 2 [UK]', 'KLI Music HD', 'MTV', "MTV 00's PT",
        'MTV 00s', 'MTV 00s RO', 'MTV 80s', 'MTV 80s RO', 'MTV 90s', 'MTV Aitio HD SE', 'MTV Base HD',
        'MTV Base UK', 'MTV Classic', 'MTV Classic USA', 'MTV Club', 'MTV Dance [RO]', 'MTV HD CA',
        'MTV HD [DE]', 'MTV HD [UK]', 'MTV Hits', 'MTV Hits RO', 'MTV Hits [RO]', 'MTV Hits [UK]',
        'MTV Idol HD', 'MTV India IN', 'MTV Live HD', 'MTV Live HD orig', 'MTV Live [UK]', 'MTV MUSIC IL',
        'MTV Music UK', 'MTV POLSKA PL', 'MTV POLSKA [PL]', 'MTV Pulse HD', 'MTV RO', 'MTV SE',
        'MTV Viihde HD FI', 'MTV Viihde HD SE', 'Music Box Gold', 'Music Box Russia', 'Music Box Russia HD',
        'Music Box Russia orig', 'Music Channel [IL]', 'Music Channel RO', 'MusicBox GE', 'MUSIC',
        'MUSIC 24', 'MUSIC 24 IL', 'music', 'music 24', 'Now 80s HD UK', 'Now 90s HD UK', 'NOW 70s UK',
        'Prokop TV Music', 'Public Music IN', 'Retro Music TV HD CZ', 'Rock Classics', 'Sky High Concert HD',
        'Sochi Music HD', 'Stingray', 'Stingray Hot Country HD', 'Stingray Hit List HD',
        'Stingray Pop Adult HD', 'SUN Music IN', 'VB MTV Old Россия HD', 'VF Music',
        'VOX MUSIC TV [PL]', 'Vox Music TV PL', 'Yosso TV Music Hits', 'Z!Music HD',
        'ТНТ Music', 'ТНТ Music HD', 'ТНТ Music orig',
        'IL: MTV Hits', 'IL: MTV Isreal', 'IL: Music IL FHD', 'IL: Music IL HD', 'IL: VH1', 'IL: VH1 Classic',
        'ערוץ 24', 'מוזיקה 24', 'מיוזיק 24', 'MTV ישראל', 'וי אייץ 1', 'VH1', 'מוסיקה'
    ],

    # ========================
    # קיימות - טבע ודוקו
    # ========================
    'Nature🌴': [
        'Discovery', 'Travel Channel', 'DISCOVERY CHANNEL HD IL', 'Nat Geo HD', 'Nat Geo Wild', 'Animal Planet HD',
        'National Geographic [IL]', 'NET GEO_WILD HD IL', 'Sky Select 5 HD', 'NAT GEO WILD IL', 'History [IL]',
        'IETV [IL]', 'ZEE TV [IL]', 'TRAVEL CHANNEL IL', 'Animal Planet [IL]', 'National Geographic HD [IL]','Travel IL', 'National Geographic HD ',
        'NATIONAL GEOGRAPHICS HD IL', 'National Geographic IL', 'National Geographic HD IL', 'IL: Animal Planet',
        'Discovery HD [IL]', 'Nat Geo Wild HD [IL]', 'Travel Channel [IL]',
        'IL: Animal planet', 'IL: Discovery HD', 'IL: Investigation Discovery', 'IL: Travel Channel',

        # תוספות בעברית
        'ערוץ דיסקברי', 'דיסקברי צאנל', 'נשיונל גיאוגרפיק', 'נשיונל גאוגרפיק', 'נט ג׳יו', 'נט ג׳יו ויילד',
        'אנימל פלאנט', 'טרוול צ׳אנל', 'ID', 'איי די', 'אינבסטיגיישן דיסקברי', 'ערוץ ההיסטוריה'
    ],

    # ========================
    # קיימות - סדרות עולם ומדיה ים תיכוני ללא ערבית
    # ========================
    'World Series🌍': [
        'Viva Premium HD IL', 'Turkish Dramas 3 HD IL', 'Turkish Dramas 2 HD IL', 'Turkish Dramas Plus HD IL',
        'Viva', 'Yam Tihoni 25', 'Viva plus', 'Aruch Sdarot Hahodiot', 'Yam Tihoni Plus', 'Vamos HD',
        'Yam Tihoni HD', 'Yam Tihoni 2', 'Viva+ IL', 'Viva+', 'Viva Vintage', 'Star channel [IL]',
        'Mediterranean [IL]', 'Bollywood [IL]', 'Turkish Dramas Plus HD [IL]', 'VIVA IL', 'Yamtihoni IL',
        'VIVA HD IL', 'VIVA+ IL', 'The Mediterranean HD [IL]', 'The Mediterranean [IL]',
        'The Mediterranean+ HD [IL]', 'BOLLYWOOD HD IL', 'BOLLYSHOW HD IL', 'Bollywood HD',
        'Turkish Dramas 2 FHD IL', 'Turkish Dramas 3 FHD IL', 'Turkish Dramas Plus FHD IL',
        'Turkish Dramas Plus IL', 'Yam Tichoni HD IL', 'Yam Tichoni IL', 'Yam Tichoni+ HD IL',
        'IL: Turkish Drama HD', 'IL: Turkish Drama 2','Bollywood IL', 'Turkish Dramas','LFC TV IL',
        'Bollywood HD [IL]', 'Turkish Dramas 2 HD [IL]', 'Turkish Dramas 2 [IL]',
        'Turkish Dramas 3 HD [IL]', 'Turkish Dramas Plus [IL]', 'Viva Plus [IL]',
        'Viva Premium HD [IL]', 'Viva Vintage [IL]', 'Viva [IL]', 'IL: Free Movies 10 Stars HD',
        'IL: Spanish Drama Channel 1 HD', 'IL: Spanish Drama Channel 2 HD', 'IL: Turkish Drama Plus', 'IL: Turkish Drama 3',
        'IL: Bollywood HD', 'IL: VIVA', 'IL: VIVA Plus', 'IL: Viva Telenovelas',
        'IL: Viva Istanbul FHD', 'IL: Bollywood Cinema India FHD', 'IL: Bollywood Serial FHD',
        'IL: Turkish Dramas FHD', 'IL: Turkish Dramas 2',
        'ויוה', 'ויוה פלוס', 'ויוה פרימיום', 'ויוה וינטג', 'טלנובלות', 'לטינו', 'סדרות ספרדיות', 'סדרות טורקיות',
        'בוליווד', 'סדרות הודיות', 'ים תיכוני', 'מדיטרניאן'
    ],

    'Sting🐝': [
        'Sting', 'STING', 'Sting TV', 'StingTV', 'Yes Sting', 'Yes STING',
        'סטינג', 'סטינג טיוי', 'סטינג TV', 'סטינג טלוויזיה',
        'Sting Action', 'Sting Comedy', 'Sting Drama', 'Sting Kids', 'Sting Movies',
        'יס סטינג'
    ],
    'Next➡️': [
        'Next', 'NEXT', 'Next TV', 'NextTV', 'Yes Next', 'YES Next',
        'נקסט', 'נקסט טיוי', 'נקסט TV', 'נקסט טלוויזיה',
        'Next Action', 'Next Comedy', 'Next Drama', 'Next Kids', 'Next Movies',
        'יס נקסט'
    ],

    # ========================
    # קטגוריות חדשות - מילות מפתח כלליות בעברית ואנגלית
    # ========================
    'Series': [
        'סדרות', 'דרמה', 'קומדיה', 'עונה', 'פרק', 'מיני סדרה',
        'Yes TV Drama', 'Yes TV Comedy', 'Yes TV Action', 'HOT3', 'HOT בידור', 'Viva'
    ],
    'Reality': [
        'ריאליטי', 'האח הגדול', 'נינגה ישראל', 'הכוכב הבא', 'מאסטר שף', 'דה ווייס', 'דה מסיכה', 'דה סטאר', 'Love Island'
    ],
    'Lifestyle': [
        'לייף סטייל', 'בית ועיצוב', 'טיפוח', 'אוכל ובישול', 'טיולים', 'Good Life', 'Home Plus', 'Fashion TV', 'ערוץ האוכל', 'פודי'
    ],
    'Science': [
        'מדע', 'דוקומנטרי', 'היסטוריה', 'טבע', 'חקר', 'ניסוי', 'Discovery', 'National Geographic', 'Nat Geo Wild', 'Animal Planet'
    ],
    'Religion': [
        'קבלה', 'יהדות', 'תורה', 'שידורי מורשת', 'Kabbalah TV', 'Hidabroot'
    ],
    'Business': [
        'עסקים', 'כלכלה', 'שוק ההון', 'בורסה', 'Fox Business'
    ],
    'Tech': [
        'טכנולוגיה', 'חדשנות', 'גאדגטים', 'Startup', 'AI', 'Tech'
    ],
    'Cooking': [
        'בישול', 'מטבח', 'מתכונים', 'Foody', 'Food Network', 'ערוץ האוכל'
    ],
    'Travel': [
        'טיולים', 'מסעות', 'תיירות', 'Travel Channel', 'ערוץ הטיולים'
    ],
    'Health': [
        'בריאות', 'כושר', 'רפואה', 'ערוץ הבריאות', 'Health Channel'
    ],
    'Education': [
        'חינוך', 'לימוד', 'אוניברסיטה', 'קמפוס', 'ערוץ חינוכית', 'כאן חינוכית'
    ],
    'Gaming': [
        'גיימינג', 'אי ספורט', 'Esports', 'Twitch', 'Gaming'
    ],
    'Anime': [
        'אנימה', 'מאנגה', 'Anime'
    ],
    'Radio': [
        'רדיו', 'Radio', 'FM', 'AM', 'Webradio'
    ],
    '24/7': [
        '24/7', '24x7', 'Non Stop', 'ללא הפסקה', 'שידור רציף'
    ],
}

# מיפויים בעברית לשמות הקבוצות
CATEGORY_KEYWORDS_HE = {
    '📰 חדשות': CATEGORY_KEYWORDS_EN['News📺'],
    '🔥 HOT Series': CATEGORY_KEYWORDS_EN['Hot🔥'],
    '👑 Yes Premium': CATEGORY_KEYWORDS_EN['Yes👑'],
    '🌈 Partner Tv': CATEGORY_KEYWORDS_EN['Partner🌈'],
    '🐶 Cellcom Tv': CATEGORY_KEYWORDS_EN['Cellcom🐶'],
    '☀️ Free-TV': CATEGORY_KEYWORDS_EN['Free Tv🌞'],
    '⚽ ספורט ישראלי': CATEGORY_KEYWORDS_EN['Sports🏀'],
    '🧒 ערוצי ילדים': CATEGORY_KEYWORDS_EN['Kids🍦'],
    '🎭 בידור': CATEGORY_KEYWORDS_EN['Entertainment🧸'],
    '🎶 מוזיקה': CATEGORY_KEYWORDS_EN['Music🎵'],
    '🌿 טבע ודוקו': CATEGORY_KEYWORDS_EN['Nature🌴'],
    '📺 סדרות זרות': CATEGORY_KEYWORDS_EN['World Series🌍'],
    'סטינג': CATEGORY_KEYWORDS_EN['Sting🐝'],
    'נקסט': CATEGORY_KEYWORDS_EN['Next➡️'],

    # קטגוריות חדשות בעברית
    '🎬 סדרות': CATEGORY_KEYWORDS_EN['Series'],
    '🎯 ריאליטי': CATEGORY_KEYWORDS_EN['Reality'],
    '🏠 לייף סטייל': CATEGORY_KEYWORDS_EN['Lifestyle'],
    '🔬 מדע': CATEGORY_KEYWORDS_EN['Science'],
    '⭐ דת': CATEGORY_KEYWORDS_EN['Religion'],
    '💼 עסקים': CATEGORY_KEYWORDS_EN['Business'],
    '💻 טכנולוגיה': CATEGORY_KEYWORDS_EN['Tech'],
    '🍳 בישול': CATEGORY_KEYWORDS_EN['Cooking'],
    '✈️ טיולים': CATEGORY_KEYWORDS_EN['Travel'],
    '💪 בריאות': CATEGORY_KEYWORDS_EN['Health'],
    '🎓 חינוך': CATEGORY_KEYWORDS_EN['Education'],
    '🎮 גיימינג': CATEGORY_KEYWORDS_EN['Gaming'],
    '🎌 אנימה': CATEGORY_KEYWORDS_EN['Anime'],
    '📻 רדיו': CATEGORY_KEYWORDS_EN['Radio'],
    '🔁 24/7': CATEGORY_KEYWORDS_EN['24/7'],
}

# =========================
# Adult-safety keyword sets
# =========================

# דפוסים לחסימה (Regex, באנגלית ועוד שפות נפוצות)
ADULT_BLOCKLIST = [
    r"\bxxx\b", r"x\s*x\s*x", r"\b18\s*\+|\b18\s*plus\b",
    r"\bsex\b", r"\bsexo\b", r"\bseks\b",
    r"\bpor(n|no|nog)\b", r"\bhentai\b",
    r"\berot(ic|ika|ico|isch|yczn|yczny)\b",
    r"\bfetish\b", r"\bnude\b", r"\bmilf\b",
    r"\bbw\b", r"\bbrazzers\b", r"\bplayboy\b",
    r"\bhustler\b", r"\bdorcel\b", r"\bsextreme\b",
    r"\bprive\b", r"\bred\s*light\b", r"\bvenus\b",
    r"\bsexy\b", r"\bextasy\b", r"\bsexysat\b",
    r"\bprivate\s*tv\b", r"\bxxl\b"
]

# חריגים בטוחים שבהם המילה "adult" אינה תכנים למבוגרים בלבד
ADULT_WHITELIST = [
    "adult swim",
    "pop adult",
    "adult contemporary"
]


# ------------------------------
# EXTRA keywords (auto-learned)
# אל תמחק - מתעדכן אוטומטית
EXTRA_CATEGORY_KEYWORDS_HE = {
    "News📺": [
        "Knesset Channel IL",
        "IL: Channel 12 FHD",
        "כאן חדשות",
        "עכשיו 14",
        "ערוץ 11",
        "כנסת",
        "Channel 9 HD",
        "Knesset FHD",
        "ערוץ 24",
        "KHAN 11",
        "C13 Keshet IL",
        "IL: Channel 12 HD",
        "IL: Channel 14 4K",
        "IL: Channel 9 FHD",
        "Reshet 13 IL",
        "ערוץ הכנסת",
        "CHANNEL 12 HD IL",
        "IL: Kneest",
        "IL: Channel 9",
        "Reshet 13 HD [IL]",
        "Channel 13",
        "כאן 11",
        "Kan Educational HD IL",
        "חדשות 13",
        "Channel 9",
        "i24 IL",
        "Knesset",
        "Channel 14",
        "Keshet 12 HD IL",
        "Kan Educational HD [IL]",
        "Now 14 HD [IL]",
        "KAN 11 [IL]",
        "CHANNEL 9 HD IL",
        "IL: Channel 14 HD",
        "Kan Chinuchit 23",
        "רשת13",
        "i24 News",
        "KAN23 [IL]",
        "Channel 9 HD IL",
        "Knesset [IL]",
        "Keshet 12 [IL]",
        "כאן 23",
        "כאן11",
        "IL: Israel HD",
        "ישראל פלוס אינטרנשיונל",
        "13 Keshet IL",
        "Now 14",
        "KAN 11 HD [IL]",
        "9 Channel IL",
        "i24",
        "KAN 11 IL",
        "Channel 98 IL",
        "Kan 11 HD IL",
        "רשת 13",
        "מוזיקה 24",
        "IL: Channel 13 HD",
        "Reshet 13 HD IL",
        "Kan Educational IL",
        "כאן חינוכית",
        "I24 News [IL]",
        "ID",
        "IL: Channel 24",
        "חדשות 12",
        "ישראל פלוס",
        "Reshet 13 [IL]",
        "i24NEWS",
        "קשת12",
        "IL: Kabbalah TV",
        "Kan 11 IL",
        "קשת 12",
        "IL: Channel 13 SD",
        "מיוזיק 24",
        "Keshet 12 FHD IL",
        "KAN 14 IL",
        "IL: Channel 24 4K",
        "CBS reality [IL]",
        "Channel 12",
        "ערוץ 14",
        "IL: Channel 12 4K",
        "Keshet 12 IL",
        "IL: Channel 13 4K",
        "CHANNEL 13 HD",
        "IL: Channel 24 FHD",
        "קבלה טי וי",
        "Channel 24",
        "חדשות12",
        "הכל כלול 13",
        "12 Keshet IL",
        "IL: Channel 12 SD",
        "Channel 11",
        "IL: Kalkala 10 HD",
        "IL: Channel 13 FHD",
        "ערוץ 9",
        "Keshet 12 HD [IL]",
        "Channel 9 IL",
        "כאן 11 HD",
        "כלכלה 10",
        "IL: Channel 9 4K",
        "חדשות13"
    ],
    "Hot🔥": [
        "הוט בידור ישראלי",
        "IL: HOT Viva Premium",
        "HOT3 HD",
        "IL: HOT HBO HD",
        "HoT",
        "Hot HBO",
        "IL: HOT Bidur",
        "IL: HOT Turkish Drama 1",
        "HOT cinema 3",
        "HOT Cinema 1 HD IL",
        "IL: HOT Cinema 1 FHD",
        "HOT cinema 2",
        "IL: HOT Cinema 1 HD",
        "IL: HOT Yam Tichoni plus",
        "IL: HOT 8 HD",
        "HOT cinema 1",
        "IL: HOT Cinema 2",
        "IL: HOT 3 HD",
        "IL: HOT Turkish Drama 2",
        "הוט סטייל",
        "IL: HOT Yam Tichoni",
        "IL: HOT Viva Vintage",
        "IL: HOT Design",
        "HOT CINEMA 1",
        "IL: HOT Vamos",
        "HOT סרטים 4",
        "IL: HOT Cinema 4 HD",
        "HOT 8 HD",
        "IL: HOT Comedy Central HD",
        "HOT CINEMA 4",
        "הוט זון",
        "HOT COMEDY CENTRAL",
        "IL: HOT Nofesh",
        "הוט קידז",
        "IL: HOT ZONE HD",
        "IL: HOT Cinema 2 FHD",
        "IL: HOT Cinema 4",
        "IL: HOT Cinema 1",
        "IL: HOT Cinema 4 FHD",
        "IL: HOT Cinema 2 HD",
        "IL: HOT Turkish Drama 3",
        "קומדי סנטרל",
        "HOT קומדי סנטרל",
        "IL: HOT Zero One 1",
        "HOT עיצוב",
        "IL: HOT Zoom Toom",
        "HOT נופש",
        "IL: HOT Cinema 3 HD",
        "הוט נופש",
        "IL: HOT Cinema 3 FHD",
        "HOT בוליווד",
        "HOT CINEMA 3",
        "הוט 3",
        "HOT",
        "HOT סרטים 3",
        "HOT סרטים 2",
        "הוט 8",
        "HOT CINEMA",
        "IL: HOT Bollywood HD",
        "IL: HOT Cinema Family FHD",
        "IL: HOT Style",
        "hot-IL",
        "IL: HOT HBO FHD",
        "IL: HOT Bollyshow",
        "IL: HOT Zero One 2",
        "HOT סרטים 1",
        "IL: HOT Kidz",
        "IL: HOT Cinema 3",
        "IL: HOT Reality",
        "הוט בידור"
    ],
    "Yes👑": [
        "IL: YES Movies Comedy HD [Multi-Sub]",
        "IL: YES Movies Drama HD [Multi-Sub]",
        "yes Movies",
        "IL: YES Movies Kids FHD",
        "יס אקשן",
        "IL: YES SPORT 4 HD",
        "IL: Yes Wiz",
        "IL: YES TV Drama FHD",
        "יס ילדים",
        "יס דרמה",
        "יש טיוי",
        "IL: YES TV Kids HD",
        "YES",
        "IL: YES TV Action HD",
        "Yes TV Drama HD",
        "IL: YES TV Comedy HD",
        "IL: YES TV Kids FHD",
        "IL: YES SPORT 1 ToGo FHD",
        "Yes",
        "יס דוקו",
        "IL: YES Movies Drama FHD",
        "יס קומדי",
        "יס פלוס",
        "IL: YES Docu HD",
        "IL: YES Movies Action HD [Multi-Sub]",
        "Yes Wiz",
        "Yes_IL",
        "יס טיוי",
        "IL: YES Cinema HD [Multi-Sub]",
        "yes Comedy",
        "Yes+",
        "IL: YES Cinema HD",
        "יס קידס",
        "IL: YES SPORT 1 HD",
        "yes Kids",
        "Yes E",
        "IL: YES Movies Comedy FHD",
        "IL: YES TV Drama HD [Multi-Sub]",
        "IL: YES SPORT 2 ToGo FHD",
        "יס מוביז",
        "IL: YES Docu FHD",
        "yes Oh",
        "IL: YES+ Cinema FHD",
        "yes",
        "YES HD IL",
        "IL: YES TV Comedy FHD",
        "yes Israeli Cinema HD",
        "יס סינמה",
        "IL: YES TV Kids HD [Multi-Sub]",
        "IL: YES SPORT 4 FHD",
        "IL: YES TV Drama HD",
        "IL: YES SPORT 3 HD",
        "IL: YES TV Comedy HD [Multi-Sub]",
        "IL: YES SPORT 2 FHD",
        "Sport-IL",
        "YES TV",
        "IL: YES TV Action HD [Multi-Sub]",
        "IL: YES Movies Drama HD",
        "yes Action",
        "יס",
        "IL: YES SPORT 2 HD",
        "IL: YES Docu HD [Multi-Sub]",
        "yes Cinema",
        "IL: YES Movies Kids HD [Multi-Sub]",
        "IL: YES+ Diamonds FHD",
        "YES_IL",
        "yes Drama",
        "IL: YES Movies Action HD",
        "יס סרטים",
        "yes Docu",
        "IL: YES SPORT 3 FHD",
        "יס או או",
        "IL: YES TV Action FHD",
        "יס או",
        "IL: YES Movies Action FHD",
        "IL: YES Movies Comedy HD",
        "IL: YES SPORT 1 FHD",
        "יס ויז",
        "yes tv"
    ],
    "Partner🌈": [
        "Partner Sratim",
        "פרטנר סדרות",
        "IL: Partner TV Netflix",
        "Partner TV",
        "Partner Yladim",
        "פרטנר סרטים",
        "IL: Kan11 HD",
        "פרטנר קומדי",
        "IL: Partner TV Movies",
        "IL: Partner TV Kids",
        "Partner Sdarot",
        "IL: Partner TV Comedy",
        "פרטנר TV",
        "IL: Partner TV Series",
        "פרטנר ילדים",
        "פרטנר טיוי"
    ],
    "Cellcom🐶": [
        "IL: Cellcom TV Isreal",
        "Cellcom HBO HD",
        "סלקום ילדים",
        "Cellcom Doco HD",
        "סלקום TV",
        "Cellcom Sratim",
        "סלקום טיוי",
        "סלקום HBO",
        "IL: Cellcom TV Kids",
        "Cellcom Rus",
        "Cellcom Yeladim",
        "סלקום סרטים",
        "סלקום משפחה",
        "סלקום דוקו",
        "Cellcom Israel",
        "IL: Cellcom TV Family",
        "IL: Cellcom TV HBO",
        "IL: Cellcom TV Movies",
        "IL: Cellcom TV Now",
        "IL: Cellcom TV Yvin"
    ],
    "Free Tv🌞": [
        "Free Tv Comedy HD",
        "IL: FreeTV Movies 10 Stars FHD",
        "Free Movies Drama HD",
        "Free Movies Family HD",
        "Free Tv Feel Good",
        "IL: FreeTV Movies Family FHD",
        "Free Movies Romantic HD",
        "IL: FreeTV Movies Action FHD",
        "ערוצי סטרים חינם",
        "IL: FreeTV Asuta Doc FHD",
        "IL: Free Movies 10 Stars HD",
        "IL: FreeTV Movies Romance FHD",
        "FreeTV",
        "Free Tv Kohav Haba HD",
        "IL: FreeTV Imagin Drama FHD",
        "Free Movies Horror HD",
        "IL: FreeTV Series Global FHD",
        "ערוצי פרי",
        "IL: FreeTV Israeli Movies FHD",
        "חינמי",
        "Free Israeli Movies HD",
        "IL: FreeTV Imagin lifestyle FHD",
        "IL: FreeTV Imagin Doco FHD",
        "Free Tv Cooking HD",
        "Free Movies Action HD",
        "Free Movies Comedy HD",
        "פרי טיוי",
        "IL: FreeTV Movies Horror FHD",
        "Free Tv Karaoke HD",
        "IL: FreeTV Imagin Cooking FHD",
        "Free Series Global HD",
        "Free Tv Hatuna HD",
        "Free Tv Drama HD",
        "IL: FreeTV Imagin Comedy FHD",
        "IL: FreeTV Movies Comedy FHD",
        "IL: FreeTV Movies Drama FHD",
        "Free Tv Lifestyle HD",
        "Free Tv Doco HD",
        "ערוצי חינם"
    ],
    "Sports🏀": [
        "MMA-TV.com orig",
        "Sport 5",
        "Sport 4 HD",
        "EXTREME",
        "IL: Sport 5 FHD P50",
        "Sport 5 HD IL ",
        "IL: Trace Spôrt Stars",
        "IL: ONE 2 FHD",
        "SPORT",
        "5 סטארס",
        "IL: Sport 5+ Stars 4K",
        "IL: Fox Sport HD",
        "DOCO Sports",
        "יורוספורט 2",
        "ערוץ הספורט",
        "יורוספורט 1",
        "Sport 1",
        "IL: ONE 2 4K",
        "IL: ONE 2 HD",
        "Edge",
        "MMA-TV.com HD",
        "Eurosport 2",
        "Sport 4",
        "Sport 2",
        "IL: Sport 5+ Plus 4K",
        "ONE ",
        "IL: Sport 5+ 4K",
        "Sport 1 HD",
        "ספורט1",
        "5 פלוס",
        "nba",
        "Eurosport 1 HD",
        "IL: Sport 5 Plus FHD",
        "Sport 5 HD",
        "IL: Eurosport 1 HD",
        "חמש לייב",
        "IL: Sport 5+ Gold 4K",
        "IL: Sport 5+ Stars HD",
        "IL: Sport 5 SD",
        "ספורט5",
        "ESPN 2 HD USA",
        "IL: Sport 5+ Live FHD",
        "ערוץ האקסטרים",
        "Red Bull TV",
        "SPORT 2 HD IL",
        "IL: Sport 5 Plus",
        "ONE 2 HD IL",
        "ספורט 2",
        "ONE2 HD [IL]",
        "Sport 5+ Live HD IL",
        "Sport 1 HD IL",
        "IL: ONE 2 FHD P50",
        "MMA-TV.com",
        "ONE 1",
        "ONE 2",
        "IL: ONE 1 FHD P50",
        "Sport 2 HD",
        "חמש גולד",
        "IL: Sport 5+ Live 4K",
        "ONE2  [IL]",
        "ספורט4",
        "IL: ONE 1 FHD",
        "wwe",
        "IL: Sport 5+ Stars FHD",
        "ספורט 5",
        "חמש פלוס",
        "ONE2 HD IL",
        "ONE2",
        "IL: Sport 5 4K",
        "חמש פלוס לייב",
        "Red Bull TV HD",
        "5 גולד",
        "IL: ONE DOCO FHD",
        "Sport_il",
        "Sport-IL",
        "WWE Russian",
        "Sport 3 HD IL",
        "NHL",
        "Sport 3 HD",
        "IL: ONE EDGE FHD",
        "IL: Sport 5 HD",
        "ספורט 4",
        "WWE Network HD",
        "5 Live IL",
        "Sport 5 Live HD",
        "IL: Sport 5+ Live FHD P50",
        "ספורט 3",
        "ספורט 1",
        "IL: ONE 1 HD",
        "ספורט2",
        "Sport",
        "5 פלוס לייב",
        "NBA",
        "EXTREME IL",
        "IL: ONE 1 4K",
        "IL: Sport 5+ Live HD",
        "ONE1",
        "IL: Eurosport 2 HD",
        "Sport 3",
        "IL: Sport 5+ UHD 4K",
        "ספורט3",
        "חמש סטארס",
        "ONE HD",
        "ONE1 HD IL",
        "IL: Sport 5 FHD",
        "ESPN USA",
        "IL: Sport 5+ Stars FHD P50",
        "IL: Sport 5 Gold",
        "IL: Extreme Sports"
    ],
    "Kids🍦": [
        "IL: Kids Channel FHD",
        "IL: Baby FHD",
        "IL: JLTV HD",
        "IL: Nick Jr",
        "טין ניק",
        "IL: DIY Channel FHD",
        "IL: Yalduti HD",
        "Nick Jr",
        "דיסני גוניור",
        "Disney Junior",
        "ניק",
        "LULI IL",
        "ZOOM",
        "ניק גוניור",
        "זום טון",
        "IL: Yalduti FHD",
        "Luli",
        "HOP CHILDHOOD IL",
        "Baby TV",
        "Luli [IL]",
        "Nick Jr [IL]",
        "IL: Yalduti Songs FHD",
        "IL: Luli",
        "NICK HD IL",
        "ערוץ הילדים",
        "Hop",
        "Junior [IL]",
        "IL: Disney Jr",
        "הופ הורים",
        "IL: Israel Shopping Channel",
        "Hop!",
        "הופ",
        "Junior",
        "Yaldut IL",
        "hop",
        "WIZ IL",
        "IL: HOP Pele FHD",
        "Hop Pele HD",
        "Baby TV [UK]",
        "Wiz",
        "לולי",
        "ZOOM [IL]",
        "TeenNick [IL]",
        "Nickelodeon [IL]",
        "Yoyo [IL]",
        "זום",
        "hop IL",
        "Jim Jam",
        "IL: HOP",
        "Disney Jr [IL]",
        "Israelit",
        "Zoom Toon HD",
        "FOMO [IL]",
        "YoYo",
        "HOT A+ Kids",
        "Yalduti",
        "IL: YOYO FHD",
        "Disney Jr IL",
        "יויו",
        "KIDS HD IL",
        "IL: HOP YALDUT",
        "IL: Disney HD",
        "IL: Junior",
        "Yaldut",
        "Nickelodeon",
        "IL: Nickelodeon",
        "BABY TV IL",
        "Baby IL",
        "NICK JR HD IL",
        "DISNEY CHANNEL",
        "ניקלודיאון",
        "Disney HD",
        "IL: Zoom",
        "DISNEY JR IL",
        "IL: Junior FHD",
        "TeenNick",
        "TeenNick IL",
        "Nick HD",
        "לוגי",
        "Kids IL",
        "ZOOM IL",
        "Disney Channel H",
        "IL: A+ Kids",
        "Hop! Childhood",
        "הופ ילדות ישראלית",
        "Junior IL",
        "HOP [IL]",
        "Zoom",
        "IL: NickTeen",
        "Disney [IL]",
        "HOP HD IL",
        "Nick Jr IL",
        "Hop Israeli Childhood",
        "IL: Baby TV",
        "IL: logi FHD",
        "Baby [IL]",
        "IL: Logi",
        "Logi",
        "דיסני",
        "דיסני קידס",
        "ZOOM TOON [IL]",
        "Disney Jr.",
        "JUNIOR IL",
        "Nick Jr HD",
        "IL: A+ kids",
        "Baby"
    ],
    "Entertainment🧸": [
        "IL: Humor Chanenel",
        "IL: Big Brother 26 FHD",
        "HUMOR CHANNEL",
        "IL: Classic FHD",
        "Fomo",
        "IL: Health Channel",
        "CANAL+ FAMILY HD PL",
        "ערוץ האופנה",
        "IL: Ninja POPUP FHD",
        "Foody HD [IL]",
        "Reality HD",
        "TLC HD",
        "RedBull TV [UK]",
        "Game Show Channel HD IL",
        "IL: Humor Channel",
        "IL: Savri FHD",
        "IL: GTV",
        "Polsat HD",
        "IL: A Plus FHD",
        "HEALTH CHANNEL",
        "IL: Lifetime",
        "IL: National Geo Wild HD",
        "EGO TOTAL HD IL",
        "Food Channel HD",
        "Ego Total [IL]",
        "IL: Big Brother 26",
        "Entertainment IL",
        "פודי",
        "Humor Channel",
        "Foody HD",
        "ZONE HD",
        "IL: Ego Total",
        "IL: National Geographic",
        "Health",
        "IL: Horse and Country TV",
        "Fashion TV",
        "IL: Extreme",
        "IL: National Geo Wild",
        "IL: Starz FHD",
        "Holiday channel [IL]",
        "Good Life [IL]",
        "Ego Total",
        "Star channel [IL]",
        "IL: Food Channel",
        "פוד נייטוורק",
        "IL: GoodLife",
        "IL: Erez Nehederet FHD",
        "IL: CBS Reality",
        "Health channel [IL]",
        "IL: Holiday channel",
        "IL: Me TV",
        "Love Island",
        "The Food Channel [IL]",
        "ערוץ הבריאות",
        "ערוץ ההיסטוריה",
        "Food Channel",
        "Star Channel",
        "IL: Fox Business HD",
        "Fashion",
        "STARS HD IL",
        "IL: National Geographic HD",
        "Good Life",
        "CBS Reality",
        "ריאליטי",
        "Savri HD",
        "Israeli Fashion [IL]",
        "נינגה ישראל",
        "Home Plus",
        "Arutz Haofna Haisraeli HD IL",
        "History HD",
        "E! IL",
        "IL: Hatunami POPUP FHD",
        "Humor Channel HD [IL]",
        "IL: Stars",
        "IL: E! Entertainment",
        "LIFETIME HD IL",
        "הכוכב הבא",
        "Boomerang",
        "IL: Next Star POPUP FHD",
        "IL: TLC",
        "IL: Home Plus",
        "החיים הטובים",
        "IL: Reality HD",
        "ערוץ ההומור",
        "Erez Nehederet HD",
        "STARS IL",
        "Home Plus IL",
        "IL: Fashion Isreal HD",
        "האח הגדול",
        "IL: Food Network HD",
        "IL: Game Show",
        "IL: Together HD",
        "E!",
        "IL: BBC entertainement",
        "Horse and Country TV",
        "A+ HD IL",
        "IL: Israeli Fashion",
        "IL: History",
        "IL: The Humor Channel",
        "5Stars HD IL",
        "IL: Travel HD",
        "תעלומות",
        "E! [IL]",
        "HISTORY HD IL",
        "ערוץ האוכל",
        "FOOD CHANNE IL",
        "IL: Fomo FHD"
    ],
    "Music🎵": [
        "Disco Polo Music PL",
        "Clarity4K Latin music",
        "Music Box Russia",
        "MTV Hits [UK]",
        "ערוץ 24",
        "MTV Music UK",
        "C Music TV",
        "MTV ישראל",
        "Stingray Hit List HD",
        "IL: Music IL HD",
        "Bridge TV ROCK",
        "ТНТ Music HD",
        "MTV 00's PT",
        "Retro Music TV HD CZ",
        "VF Music",
        "ТНТ Music",
        "MTV 00s",
        "MTV HD [DE]",
        "MTV Base HD",
        "Fresh Dance",
        "IL: MTV Hits",
        "MTV 80s RO",
        "Music Channel RO",
        "VB MTV Old Россия HD",
        "BRIDGE TV Deluxe",
        "Bridge Hits",
        "MUSIC",
        "Stingray",
        "Europa Plus TV",
        "EU Music HD UA",
        "IL: VH1",
        "Music Box Russia orig",
        "IL: MTV HD",
        "MTV Classic",
        "music 24",
        "MTV Aitio HD SE",
        "Now 90s HD UK",
        "Fresh Concerts",
        "Classic Music HD",
        "MTV Hits [RO]",
        "MTV Live [UK]",
        "Europa Plus TV orig",
        "VOX MUSIC TV [PL]",
        "MUSIC 24",
        "Bridge Deluxe HD orig",
        "BOX Music 4K HDR",
        "IL: VH1 Classic",
        "MTV Club",
        "MTV",
        "HMTV IN",
        "MTV Pulse HD",
        "Sochi Music HD",
        "MTV Hits",
        "VH1",
        "Z!Music HD",
        "Clarity4K France music",
        "B4U Music IN",
        "MTV India IN",
        "Bridge Rock",
        "MTV POLSKA [PL]",
        "MTV Live HD",
        "Stingray Hot Country HD",
        "Music Box Russia HD",
        "1HD Music Television orig",
        "Clubbing TV HD",
        "Yosso TV Music Hits",
        "IL: MTV Isreal",
        "Music Channel [IL]",
        "IL: Music IL FHD",
        "Biz Music HD UZ",
        "IT: MTV HD",
        "ITV 2 [UK]",
        "מוזיקה 24",
        "SUN Music IN",
        "MTV 00s RO",
        "MTV 80s",
        "Bridge TV Classic",
        "MTV Idol HD",
        "Clarity4K Russian music",
        "NOW 70s UK",
        "MTV Live HD orig",
        "4ever Music HD UA",
        "music",
        "Club MTV",
        "EU Music UA",
        "Backus TV Music HD",
        "HIT MUSIC [RO]",
        "מיוזיק 24",
        "MusicBox GE",
        "MTV Base UK",
        "CHANNEL 24 MUSIC HD IL",
        "KLI Music HD",
        "BRIDGE TV Русский Хит",
        "MTV Hits RO",
        "מוסיקה",
        "MUSIC 24 IL",
        "Sky High Concert HD",
        "MTV POLSKA PL",
        "MTV Viihde HD SE",
        "BRIDGE TV HITS",
        "Clarity4K Bollywood music",
        "Now 80s HD UK",
        "FRESH Sad Music HD",
        "Prokop TV Music",
        "Rock Classics",
        "MTV RO",
        "Bridge Deluxe HD",
        "Europa Plus TV HD",
        "Clarity4K Remastered music",
        "Vox Music TV PL",
        "Baraza Music HD",
        "Clarity4K Korean music",
        "MTV Classic USA",
        "Stingray Pop Adult HD",
        "MTV 90s",
        "MTV Viihde HD FI",
        "MTV HD [UK]",
        "MTV MUSIC IL",
        "MTV Dance [RO]",
        "Public Music IN",
        "4ever Music UA",
        "Music Box Gold",
        "וי אייץ 1",
        "MTV HD CA",
        "Classic Music",
        "ТНТ Music orig",
        "MTV SE",
        "Bridge TV"
    ],
    "Nature🌴": [
        "TRAVEL CHANNEL IL",
        "נשיונל גאוגרפיק",
        "IL: Investigation Discovery",
        "ערוץ ההיסטוריה",
        "Nat Geo HD",
        "נט ג׳יו",
        "National Geographic HD IL",
        "History [IL]",
        "Animal Planet HD",
        "Travel Channel",
        "NATIONAL GEOGRAPHICS HD IL",
        "IL: Travel Channel",
        "איי די",
        "NAT GEO WILD IL",
        "DISCOVERY CHANNEL HD IL",
        "IL: Animal planet",
        "Nat Geo Wild",
        "ID",
        "IL: Animal Planet",
        "IL: Discovery HD",
        "דיסקברי צאנל",
        "National Geographic HD [IL]",
        "Nat Geo Wild HD [IL]",
        "אינבסטיגיישן דיסקברי",
        "Sky Select 5 HD",
        "נשיונל גיאוגרפיק",
        "אנימל פלאנט",
        "ערוץ דיסקברי",
        "ZEE TV [IL]",
        "נט ג׳יו ויילד",
        "NET GEO_WILD HD IL",
        "טרוול צ׳אנל",
        "Discovery",
        "IETV [IL]",
        "Discovery HD [IL]",
        "National Geographic IL",
        "National Geographic [IL]",
        "Travel Channel [IL]",
        "Animal Planet [IL]"
    ],
    "World Series🌍": [
        "Turkish Dramas 2 HD IL",
        "IL: Turkish Drama HD",
        "Viva Vintage",
        "Turkish Dramas Plus [IL]",
        "ויוה פלוס",
        "Viva+ IL",
        "BOLLYWOOD HD IL",
        "Yam Tihoni Plus",
        "Yam Tichoni HD IL",
        "IL: Turkish Drama 2",
        "Viva [IL]",
        "IL: Bollywood Serial FHD",
        "Yam Tichoni+ HD IL",
        "IL: Spanish Drama Channel 2 HD",
        "IL: Bollywood Cinema India FHD",
        "Bollywood HD",
        "Turkish Dramas 2 [IL]",
        "The Mediterranean+ HD [IL]",
        "IL: VIVA Plus",
        "VIVA HD IL",
        "BOLLYSHOW HD IL",
        "IL: Spanish Drama Channel 1 HD",
        "Turkish Dramas 3 HD IL",
        "Yam Tihoni 25",
        "Viva",
        "Viva+",
        "Yam Tihoni 2",
        "IL: Free Movies 10 Stars HD",
        "Yam Tihoni HD",
        "IL: Turkish Drama 3",
        "סדרות ספרדיות",
        "Turkish Dramas Plus HD [IL]",
        "לטינו",
        "ויוה",
        "Turkish Dramas 2 FHD IL",
        "Viva Plus [IL]",
        "IL: Viva Istanbul FHD",
        "IL: Turkish Dramas FHD",
        "Turkish Dramas 2 HD [IL]",
        "The Mediterranean HD [IL]",
        "ויוה וינטג",
        "IL: Turkish Dramas 2",
        "מדיטרניאן",
        "IL: Turkish Drama Plus",
        "Viva plus",
        "טלנובלות",
        "Bollywood [IL]",
        "ויוה פרימיום",
        "Mediterranean [IL]",
        "Viva Premium HD [IL]",
        "Viva Vintage [IL]",
        "IL: VIVA",
        "Star channel [IL]",
        "Yamtihoni IL",
        "Aruch Sdarot Hahodiot",
        "VIVA+ IL",
        "Turkish Dramas Plus HD IL",
        "The Mediterranean [IL]",
        "Yam Tichoni IL",
        "בוליווד",
        "Turkish Dramas Plus FHD IL",
        "IL: Viva Telenovelas",
        "Viva Premium HD IL",
        "Turkish Dramas Plus IL",
        "Turkish Dramas 3 HD [IL]",
        "סדרות טורקיות",
        "סדרות הודיות",
        "ים תיכוני",
        "VIVA IL",
        "Vamos HD",
        "Bollywood HD [IL]",
        "IL: Bollywood HD",
        "Turkish Dramas 3 FHD IL"
    ],
    "Sting🐝": [
        "Yes Sting",
        "STING",
        "Sting TV",
        "סטינג TV",
        "Sting Drama",
        "StingTV",
        "Sting Kids",
        "Yes STING",
        "Sting Action",
        "יס סטינג",
        "סטינג טיוי",
        "Sting Comedy",
        "Sting",
        "Sting Movies",
        "סטינג טלוויזיה",
        "סטינג"
    ],
    "Next➡️": [
        "נקסט טיוי",
        "Next TV",
        "נקסט TV",
        "YES Next",
        "Next Kids",
        "נקסט טלוויזיה",
        "Next Movies",
        "יס נקסט",
        "Next",
        "נקסט",
        "Yes Next",
        "Next Drama",
        "NextTV",
        "Next Comedy",
        "NEXT",
        "Next Action"
    ],
    "Series": [
        "פרק",
        "Viva",
        "סדרות",
        "קומדיה",
        "Yes TV Action",
        "Yes TV Drama",
        "HOT3",
        "Yes TV Comedy",
        "מיני סדרה",
        "HOT בידור",
        "עונה",
        "דרמה"
    ],
    "Reality": [
        "דה מסיכה",
        "Love Island",
        "הכוכב הבא",
        "מאסטר שף",
        "דה ווייס",
        "נינגה ישראל",
        "האח הגדול",
        "דה סטאר",
        "ריאליטי"
    ],
    "Lifestyle": [
        "Fashion TV",
        "בית ועיצוב",
        "ערוץ האוכל",
        "טיפוח",
        "טיולים",
        "Good Life",
        "Home Plus",
        "לייף סטייל",
        "אוכל ובישול",
        "פודי",
        "Food Time",
        "Travel+Adventure HD",
        "Food Network Россия",
        "Food Network HD",
        "Food Network PL",
        "TVN Style PL"
    ],
    "Science": [
        "Nat Geo Wild",
        "מדע",
        "דוקומנטרי",
        "National Geographic",
        "ניסוי",
        "Discovery",
        "היסטוריה",
        "Animal Planet",
        "טבע",
        "חקר"
    ],
    "Religion": [
        "תורה",
        "קבלה",
        "Hidabroot",
        "Kabbalah TV",
        "שידורי מורשת",
        "יהדות"
    ],
    "Business": [
        "כלכלה",
        "עסקים",
        "בורסה",
        "שוק ההון",
        "Fox Business"
    ],
    "Tech": [
        "גאדגטים",
        "AI",
        "חדשנות",
        "Startup",
        "Tech",
        "טכנולוגיה"
    ],
    "Cooking": [
        "בישול",
        "מתכונים",
        "ערוץ האוכל",
        "Foody",
        "Food Network",
        "מטבח"
    ],
    "Travel": [
        "תיירות",
        "ערוץ הטיולים",
        "מסעות",
        "טיולים",
        "Travel Channel"
    ],
    "Health": [
        "רפואה",
        "כושר",
        "ערוץ הבריאות",
        "Health Channel",
        "בריאות"
    ],
    "Education": [
        "קמפוס",
        "חינוך",
        "אוניברסיטה",
        "לימוד",
        "כאן חינוכית",
        "ערוץ חינוכית",
        "Da Vinci Learning",
        "Eroluxe Schoolgirl"
    ],
    "Gaming": [
        "Esports",
        "אי ספורט",
        "גיימינג",
        "Twitch",
        "Gaming"
    ],
    "Anime": [
        "Anime",
        "מאנגה",
        "אנימה"
    ],
    "Radio": [
        "FM",
        "Webradio",
        "Radio",
        "רדיו",
        "AM",
        "Amedia 1 HD",
        "Amedia 2 HD",
        "Amedia Premium HD",
        "Amedia Hit HD",
        "Star Family HD",
        "SKY HIGH Scream",
        "Fresh Family",
        "Magic Family",
        "JimJam",
        "Eroluxe Step Family",
        "Eroluxe Creampie",
        "Star Family LV",
        "Active Family PL",
        "Polsat Games"
    ],
    "24/7": [
        "24x7",
        "Non Stop",
        "ללא הפסקה",
        "24/7",
        "שידור רציף"
    ],
    "World Italian": [
        "Viju+ Megahit HD",
        "Hinuhit",
        "Init TV LT",
        "AXN White PL",
        "KBC-Гай Ritchie & Tarantino"
    ],
    "World Turkish": [
        "SKY HIGH Strike VHS",
        "InUltra",
        "TV Extra LV",
        "13th Street HD",
        "Metro PL",
        "TV8 HD TR",
        "Show HD TR",
        "Kinoteatr",
        "Kentron"
    ],
    "World Russian": [
        "SKY HIGH Gunrush",
        "Ru.TV",
        "Eroluxe Brunette",
        "TNT PL",
        "Rustavi 2"
    ],
    "World German": [
        "SKY HIGH Undead",
        "Eroluxe Cheerleader",
        "Delfi TV LT",
        "ProSieben HD",
        "ProSieben Maxx HD"
    ],
    "World Spanish": [
        "SKY HIGH heroes",
        "ICTV 2(test)",
        "1+1 Україна(test)",
        "Penthouse Quickies",
        "Eroluxe Blondes",
        "Eroluxe Japanese",
        "Eroluxe Lesbians",
        "Eroluxe Shemales",
        "Spiegel Geschichte HD",
        "Tagesschau 24 HD",
        "Crime + Investigation PL",
        "Biznes 24 PL"
    ],
    "World Persian": [
        "SKY HIGH spirit",
        "Gulli Girl"
    ],
    "World French": [
        "SKY HIGH fresh HD",
        "SKY HIGH fresh 60",
        "Fresh Premiere",
        "Fresh Rating",
        "Fresh VHS",
        "Fresh Fantastic",
        "Fresh Adventure",
        "Fresh Romantic",
        "Fresh Soviet",
        "Fresh TV Armenia"
    ],
    "Entertainment": [
        "TLC HD",
        "World Fashion Channel",
        "Fashion TV",
        "Polsat HD",
        "CBS Reality PL"
    ],
    "Nature": [
        "Travel Channel HD"
    ],
    "Sports": [
        "NHL Network HD"
    ],
    "News": [
        "Bridge TV",
        "Bridge Deluxe",
        "Bridge TV Русский хит",
        "Bridge Фрэш",
        "VividRed HD"
    ],
    "Music": [
        "Europa Plus TV"
    ],
    "World Series": [
        "VIVA TV",
        "Viva",
        "Viva Plus"
    ],
    "World Balkans": [
        "iConcerts"
    ],
    "World Chinese": [
        "Phoenix HD"
    ],
    "Kids": [
        "Polsat Jim Jam",
        "Zoom TV PL"
    ],
    "World Portuguese": [
        "TVP Kuptura PL"
    ]
}
EXTRA_CATEGORY_KEYWORDS_EN = {
    "News📺": [
        "Keshet 12 [IL]",
        "KHAN 11",
        "כאן 11 HD",
        "קשת12",
        "חדשות13",
        "Kan Educational HD IL",
        "IL: Channel 13 4K",
        "Knesset Channel IL",
        "CHANNEL 13 HD",
        "Now 14",
        "כאן חדשות",
        "ישראל פלוס",
        "12 Keshet IL",
        "IL: Channel 13 SD",
        "כאן11",
        "Now 14 HD [IL]",
        "i24NEWS",
        "Channel 9",
        "ערוץ הכנסת",
        "IL: Channel 12 4K",
        "KAN 14 IL",
        "מוזיקה 24",
        "Reshet 13 HD [IL]",
        "KAN 11 HD [IL]",
        "IL: Channel 12 SD",
        "Keshet 12 HD IL",
        "Keshet 12 HD [IL]",
        "Channel 9 HD IL",
        "חדשות 13",
        "IL: Channel 12 FHD",
        "IL: Channel 14 4K",
        "מיוזיק 24",
        "C13 Keshet IL",
        "IL: Israel HD",
        "Kan 11 HD IL",
        "13 Keshet IL",
        "ערוץ 14",
        "Kan 11 IL",
        "Channel 24",
        "Kan Educational IL",
        "i24 News",
        "Channel 9 HD",
        "ערוץ 24",
        "IL: Channel 14 HD",
        "כאן חינוכית",
        "Channel 13",
        "Reshet 13 HD IL",
        "KAN23 [IL]",
        "Knesset FHD",
        "KAN 11 [IL]",
        "Channel 98 IL",
        "IL: Kalkala 10 HD",
        "KAN 11 IL",
        "ערוץ 9",
        "Kan Educational HD [IL]",
        "IL: Channel 9 4K",
        "IL: Channel 24 4K",
        "i24 IL",
        "IL: Channel 9",
        "כלכלה 10",
        "Keshet 12 FHD IL",
        "כאן 11",
        "Reshet 13 [IL]",
        "Keshet 12 IL",
        "IL: Channel 13 HD",
        "CHANNEL 9 HD IL",
        "ID",
        "חדשות 12",
        "IL: Kneest",
        "Kan Chinuchit 23",
        "כאן 23",
        "ישראל פלוס אינטרנשיונל",
        "9 Channel IL",
        "חדשות12",
        "קשת 12",
        "הכל כלול 13",
        "Channel 9 IL",
        "IL: Kabbalah TV",
        "ערוץ 11",
        "Channel 12",
        "I24 News [IL]",
        "Knesset",
        "IL: Channel 12 HD",
        "CBS reality [IL]",
        "CHANNEL 12 HD IL",
        "Knesset [IL]",
        "עכשיו 14",
        "Channel 11",
        "IL: Channel 9 FHD",
        "Channel 14",
        "IL: Channel 24",
        "IL: Channel 13 FHD",
        "IL: Channel 24 FHD",
        "קבלה טי וי",
        "כנסת",
        "Reshet 13 IL",
        "רשת 13",
        "רשת13",
        "i24"
    ],
    "Hot🔥": [
        "IL: HOT Yam Tichoni plus",
        "Hot HBO",
        "IL: HOT ZONE HD",
        "HOT cinema 2",
        "IL: HOT Cinema 4 HD",
        "IL: HOT Cinema 4 FHD",
        "HoT",
        "קומדי סנטרל",
        "IL: HOT Cinema 3 HD",
        "HOT",
        "הוט בידור",
        "IL: HOT Comedy Central HD",
        "HOT בוליווד",
        "IL: HOT Zero One 1",
        "IL: HOT Kidz",
        "IL: HOT Bollywood HD",
        "IL: HOT Viva Vintage",
        "IL: HOT Yam Tichoni",
        "IL: HOT Cinema 2 HD",
        "HOT 8 HD",
        "הוט 3",
        "HOT סרטים 1",
        "HOT CINEMA 4",
        "HOT COMEDY CENTRAL",
        "IL: HOT Viva Premium",
        "HOT Cinema 1 HD IL",
        "HOT cinema 1",
        "IL: HOT HBO FHD",
        "IL: HOT Cinema Family FHD",
        "IL: HOT Nofesh",
        "HOT cinema 3",
        "IL: HOT Design",
        "IL: HOT 3 HD",
        "HOT נופש",
        "HOT סרטים 2",
        "IL: HOT 8 HD",
        "הוט בידור ישראלי",
        "הוט 8",
        "IL: HOT Turkish Drama 2",
        "HOT CINEMA",
        "HOT סרטים 3",
        "IL: HOT Bollyshow",
        "hot-IL",
        "IL: HOT Cinema 2",
        "IL: HOT Zero One 2",
        "IL: HOT Style",
        "IL: HOT Vamos",
        "הוט נופש",
        "IL: HOT Reality",
        "הוט קידז",
        "IL: HOT Turkish Drama 3",
        "IL: HOT Cinema 3 FHD",
        "HOT CINEMA 3",
        "IL: HOT Cinema 4",
        "IL: HOT Turkish Drama 1",
        "IL: HOT Cinema 3",
        "HOT סרטים 4",
        "IL: HOT Cinema 1 FHD",
        "הוט זון",
        "HOT CINEMA 1",
        "HOT עיצוב",
        "IL: HOT Cinema 1",
        "IL: HOT Cinema 1 HD",
        "הוט סטייל",
        "IL: HOT Cinema 2 FHD",
        "IL: HOT Bidur",
        "IL: HOT HBO HD",
        "HOT קומדי סנטרל",
        "HOT3 HD",
        "IL: HOT Zoom Toom"
    ],
    "Yes👑": [
        "IL: YES Movies Action HD [Multi-Sub]",
        "יס קומדי",
        "יס טיוי",
        "יס או או",
        "IL: YES TV Action HD [Multi-Sub]",
        "IL: YES SPORT 1 HD",
        "יס או",
        "IL: YES Movies Drama HD",
        "IL: YES Movies Comedy FHD",
        "יס קידס",
        "IL: YES+ Cinema FHD",
        "Yes+",
        "IL: YES TV Drama HD [Multi-Sub]",
        "Yes TV Drama HD",
        "יס אקשן",
        "IL: YES Docu HD [Multi-Sub]",
        "IL: YES Movies Kids FHD",
        "IL: YES SPORT 4 FHD",
        "yes Cinema",
        "yes tv",
        "IL: YES TV Drama HD",
        "יס ילדים",
        "Yes_IL",
        "IL: YES Movies Comedy HD [Multi-Sub]",
        "yes Action",
        "IL: YES Docu FHD",
        "IL: YES TV Comedy FHD",
        "IL: YES TV Drama FHD",
        "IL: YES Movies Kids HD [Multi-Sub]",
        "IL: YES Movies Drama HD [Multi-Sub]",
        "יס ויז",
        "IL: YES TV Action HD",
        "יס סרטים",
        "IL: YES Docu HD",
        "IL: YES+ Diamonds FHD",
        "IL: YES TV Kids HD",
        "YES",
        "יס פלוס",
        "IL: YES Movies Action FHD",
        "Yes",
        "yes Comedy",
        "IL: YES Cinema HD",
        "yes Israeli Cinema HD",
        "IL: YES TV Action FHD",
        "IL: YES SPORT 4 HD",
        "yes",
        "יס",
        "יס דרמה",
        "IL: YES Cinema HD [Multi-Sub]",
        "yes Movies",
        "IL: YES SPORT 2 FHD",
        "Sport-IL",
        "IL: YES Movies Comedy HD",
        "IL: YES SPORT 2 ToGo FHD",
        "YES HD IL",
        "IL: YES SPORT 2 HD",
        "יש טיוי",
        "IL: YES SPORT 3 HD",
        "yes Drama",
        "Yes Wiz",
        "Yes E",
        "IL: YES TV Comedy HD",
        "IL: Yes Wiz",
        "יס דוקו",
        "YES_IL",
        "יס סינמה",
        "יס מוביז",
        "IL: YES Movies Action HD",
        "IL: YES Movies Drama FHD",
        "yes Oh",
        "IL: YES TV Comedy HD [Multi-Sub]",
        "YES TV",
        "IL: YES TV Kids FHD",
        "IL: YES SPORT 3 FHD",
        "yes Kids",
        "IL: YES SPORT 1 FHD",
        "IL: YES TV Kids HD [Multi-Sub]",
        "yes Docu",
        "IL: YES SPORT 1 ToGo FHD"
    ],
    "Partner🌈": [
        "פרטנר ילדים",
        "פרטנר טיוי",
        "IL: Partner TV Movies",
        "IL: Kan11 HD",
        "IL: Partner TV Comedy",
        "Partner Sdarot",
        "IL: Partner TV Series",
        "פרטנר סרטים",
        "Partner Sratim",
        "IL: Partner TV Kids",
        "פרטנר קומדי",
        "פרטנר סדרות",
        "פרטנר TV",
        "IL: Partner TV Netflix",
        "Partner Yladim",
        "Partner TV"
    ],
    "Cellcom🐶": [
        "IL: Cellcom TV Yvin",
        "IL: Cellcom TV HBO",
        "סלקום ילדים",
        "Cellcom Israel",
        "סלקום טיוי",
        "Cellcom Doco HD",
        "IL: Cellcom TV Isreal",
        "Cellcom Yeladim",
        "Cellcom HBO HD",
        "סלקום TV",
        "IL: Cellcom TV Movies",
        "IL: Cellcom TV Family",
        "IL: Cellcom TV Kids",
        "סלקום סרטים",
        "Cellcom Rus",
        "סלקום משפחה",
        "סלקום דוקו",
        "סלקום HBO",
        "IL: Cellcom TV Now",
        "Cellcom Sratim"
    ],
    "Free Tv🌞": [
        "Free Movies Romantic HD",
        "IL: FreeTV Imagin Cooking FHD",
        "IL: FreeTV Movies Comedy FHD",
        "Free Tv Doco HD",
        "IL: FreeTV Imagin Doco FHD",
        "IL: FreeTV Asuta Doc FHD",
        "Free Tv Karaoke HD",
        "IL: FreeTV Imagin Drama FHD",
        "Free Movies Comedy HD",
        "IL: FreeTV Movies Romance FHD",
        "FreeTV",
        "IL: FreeTV Israeli Movies FHD",
        "IL: Free Movies 10 Stars HD",
        "IL: FreeTV Series Global FHD",
        "Free Tv Hatuna HD",
        "IL: FreeTV Movies Family FHD",
        "IL: FreeTV Movies 10 Stars FHD",
        "Free Tv Feel Good",
        "ערוצי חינם",
        "ערוצי פרי",
        "פרי טיוי",
        "ערוצי סטרים חינם",
        "IL: FreeTV Imagin lifestyle FHD",
        "Free Movies Family HD",
        "Free Tv Comedy HD",
        "IL: FreeTV Imagin Comedy FHD",
        "Free Tv Drama HD",
        "Free Tv Cooking HD",
        "Free Movies Horror HD",
        "IL: FreeTV Movies Drama FHD",
        "Free Movies Action HD",
        "Free Israeli Movies HD",
        "Free Movies Drama HD",
        "IL: FreeTV Movies Horror FHD",
        "Free Series Global HD",
        "חינמי",
        "Free Tv Kohav Haba HD",
        "Free Tv Lifestyle HD",
        "IL: FreeTV Movies Action FHD"
    ],
    "Sports🏀": [
        "ספורט3",
        "ספורט 4",
        "IL: Sport 5 4K",
        "IL: Sport 5 Gold",
        "ספורט 1",
        "יורוספורט 2",
        "DOCO Sports",
        "Sport 3 HD IL",
        "ONE1",
        "Sport 4",
        "Sport 5 HD IL ",
        "ONE 2",
        "Eurosport 1 HD",
        "IL: Sport 5 Plus",
        "IL: ONE 1 FHD P50",
        "ONE ",
        "ONE2 HD [IL]",
        "ערוץ האקסטרים",
        "Sport 5+ Live HD IL",
        "SPORT 2 HD IL",
        "EXTREME IL",
        "Sport 2 HD",
        "IL: ONE 1 HD",
        "ספורט2",
        "WWE Network HD",
        "ספורט 3",
        "IL: Sport 5+ Gold 4K",
        "IL: Sport 5+ Stars FHD P50",
        "חמש סטארס",
        "ספורט1",
        "5 סטארס",
        "ONE1 HD IL",
        "5 פלוס",
        "wwe",
        "IL: Sport 5 FHD P50",
        "Sport 5",
        "Red Bull TV HD",
        "5 פלוס לייב",
        "EXTREME",
        "IL: Sport 5+ Stars HD",
        "IL: ONE 2 FHD P50",
        "IL: Eurosport 1 HD",
        "IL: Sport 5+ Live FHD P50",
        "ספורט4",
        "IL: Sport 5+ Plus 4K",
        "Sport 3 HD",
        "MMA-TV.com HD",
        "ESPN USA",
        "IL: ONE 2 HD",
        "IL: Extreme Sports",
        "Sport 5 HD",
        "ONE 1",
        "Sport 4 HD",
        "5 Live IL",
        "IL: Sport 5+ Stars FHD",
        "MMA-TV.com",
        "Sport 1 HD",
        "IL: Fox Sport HD",
        "Sport 2",
        "ONE2  [IL]",
        "ONE HD",
        "nba",
        "Edge",
        "5 גולד",
        "Sport 3",
        "Sport 5 Live HD",
        "NHL",
        "IL: Sport 5 HD",
        "Sport-IL",
        "IL: Trace Spôrt Stars",
        "IL: Sport 5+ Stars 4K",
        "IL: ONE 1 FHD",
        "IL: Sport 5+ Live 4K",
        "Eurosport 2",
        "ספורט 2",
        "IL: ONE DOCO FHD",
        "IL: ONE EDGE FHD",
        "IL: Sport 5+ 4K",
        "IL: Sport 5+ UHD 4K",
        "ספורט 5",
        "IL: Sport 5+ Live FHD",
        "ONE 2 HD IL",
        "יורוספורט 1",
        "IL: Sport 5 FHD",
        "IL: ONE 1 4K",
        "ONE2 HD IL",
        "חמש פלוס",
        "WWE Russian",
        "Sport",
        "NBA",
        "MMA-TV.com orig",
        "Sport 1",
        "IL: Sport 5 SD",
        "Sport_il",
        "IL: Sport 5 Plus FHD",
        "חמש לייב",
        "חמש פלוס לייב",
        "IL: Sport 5+ Live HD",
        "SPORT",
        "חמש גולד",
        "ערוץ הספורט",
        "IL: Eurosport 2 HD",
        "ספורט5",
        "Sport 1 HD IL",
        "IL: ONE 2 4K",
        "IL: ONE 2 FHD",
        "ONE2",
        "Red Bull TV",
        "ESPN 2 HD USA"
    ],
    "Kids🍦": [
        "IL: Baby FHD",
        "Disney [IL]",
        "ZOOM TOON [IL]",
        "דיסני גוניור",
        "Nick HD",
        "IL: logi FHD",
        "Baby [IL]",
        "IL: DIY Channel FHD",
        "Baby IL",
        "YoYo",
        "IL: Yalduti HD",
        "Nick Jr HD",
        "KIDS HD IL",
        "Disney Jr IL",
        "TeenNick IL",
        "HOP HD IL",
        "HOT A+ Kids",
        "ZOOM [IL]",
        "IL: A+ Kids",
        "Baby",
        "IL: Nick Jr",
        "IL: A+ kids",
        "Wiz",
        "IL: HOP YALDUT",
        "Baby TV [UK]",
        "Junior [IL]",
        "IL: HOP",
        "IL: Yalduti FHD",
        "IL: HOP Pele FHD",
        "BABY TV IL",
        "Nick Jr IL",
        "TeenNick [IL]",
        "IL: Logi",
        "Luli [IL]",
        "Disney Jr.",
        "Nickelodeon",
        "IL: Kids Channel FHD",
        "Israelit",
        "IL: Disney HD",
        "JUNIOR IL",
        "NICK HD IL",
        "ניק גוניור",
        "IL: Nickelodeon",
        "IL: YOYO FHD",
        "לולי",
        "Yoyo [IL]",
        "HOP CHILDHOOD IL",
        "דיסני קידס",
        "NICK JR HD IL",
        "לוגי",
        "ניקלודיאון",
        "WIZ IL",
        "Hop!",
        "DISNEY JR IL",
        "ZOOM IL",
        "Nick Jr",
        "IL: Zoom",
        "Baby TV",
        "HOP [IL]",
        "Disney HD",
        "Hop Israeli Childhood",
        "הופ ילדות ישראלית",
        "Hop",
        "Logi",
        "יויו",
        "IL: Disney Jr",
        "Hop! Childhood",
        "זום טון",
        "טין ניק",
        "LULI IL",
        "IL: Luli",
        "Yaldut IL",
        "hop IL",
        "הופ הורים",
        "IL: Baby TV",
        "Disney Channel H",
        "Disney Jr [IL]",
        "TeenNick",
        "ניק",
        "Hop Pele HD",
        "Junior IL",
        "hop",
        "Kids IL",
        "ערוץ הילדים",
        "IL: Yalduti Songs FHD",
        "Luli",
        "IL: Israel Shopping Channel",
        "DISNEY CHANNEL",
        "Yalduti",
        "Zoom Toon HD",
        "Junior",
        "הופ",
        "Yaldut",
        "ZOOM",
        "Nickelodeon [IL]",
        "IL: Junior FHD",
        "דיסני",
        "זום",
        "Zoom",
        "Disney Junior",
        "Nick Jr [IL]",
        "FOMO [IL]",
        "Jim Jam",
        "IL: Junior",
        "IL: NickTeen",
        "IL: JLTV HD"
    ],
    "Entertainment🧸": [
        "הכוכב הבא",
        "האח הגדול",
        "Arutz Haofna Haisraeli HD IL",
        "Love Island",
        "E! IL",
        "IL: Next Star POPUP FHD",
        "Polsat HD",
        "Ego Total [IL]",
        "IL: National Geographic",
        "The Food Channel [IL]",
        "IL: Health Channel",
        "IL: A Plus FHD",
        "ריאליטי",
        "IL: The Humor Channel",
        "IL: National Geo Wild HD",
        "IL: History",
        "IL: Humor Chanenel",
        "IL: National Geo Wild",
        "ערוץ ההיסטוריה",
        "IL: Reality HD",
        "Good Life",
        "IL: Food Channel",
        "History HD",
        "Good Life [IL]",
        "IL: TLC",
        "IL: BBC entertainement",
        "IL: Classic FHD",
        "ערוץ הבריאות",
        "IL: Stars",
        "E!",
        "IL: Me TV",
        "IL: Hatunami POPUP FHD",
        "IL: Lifetime",
        "Food Channel HD",
        "RedBull TV [UK]",
        "Horse and Country TV",
        "Ego Total",
        "A+ HD IL",
        "IL: Horse and Country TV",
        "פודי",
        "IL: Extreme",
        "ערוץ ההומור",
        "Game Show Channel HD IL",
        "FOOD CHANNE IL",
        "HEALTH CHANNEL",
        "Savri HD",
        "HISTORY HD IL",
        "Home Plus",
        "IL: CBS Reality",
        "פוד נייטוורק",
        "IL: Humor Channel",
        "Health channel [IL]",
        "Foody HD [IL]",
        "ערוץ האוכל",
        "IL: GoodLife",
        "ZONE HD",
        "IL: E! Entertainment",
        "LIFETIME HD IL",
        "5Stars HD IL",
        "STARS HD IL",
        "תעלומות",
        "Humor Channel",
        "Fashion",
        "IL: Savri FHD",
        "E! [IL]",
        "CANAL+ FAMILY HD PL",
        "IL: Ninja POPUP FHD",
        "IL: Fox Business HD",
        "IL: Home Plus",
        "IL: Big Brother 26 FHD",
        "TLC HD",
        "IL: Ego Total",
        "IL: Erez Nehederet FHD",
        "נינגה ישראל",
        "Star channel [IL]",
        "Fomo",
        "IL: Fashion Isreal HD",
        "Fashion TV",
        "IL: National Geographic HD",
        "IL: Big Brother 26",
        "IL: Israeli Fashion",
        "IL: Together HD",
        "Erez Nehederet HD",
        "IL: Travel HD",
        "Humor Channel HD [IL]",
        "IL: Holiday channel",
        "CBS Reality",
        "HUMOR CHANNEL",
        "Holiday channel [IL]",
        "Israeli Fashion [IL]",
        "IL: GTV",
        "החיים הטובים",
        "Health",
        "Home Plus IL",
        "Boomerang",
        "IL: Food Network HD",
        "Entertainment IL",
        "IL: Fomo FHD",
        "STARS IL",
        "IL: Game Show",
        "Reality HD",
        "IL: Starz FHD",
        "EGO TOTAL HD IL",
        "Star Channel",
        "ערוץ האופנה",
        "Food Channel",
        "Foody HD"
    ],
    "Music🎵": [
        "MTV Live [UK]",
        "MTV 80s RO",
        "VH1",
        "MTV POLSKA PL",
        "Clarity4K France music",
        "MTV 80s",
        "MTV Live HD orig",
        "HMTV IN",
        "Baraza Music HD",
        "CHANNEL 24 MUSIC HD IL",
        "1HD Music Television orig",
        "MTV",
        "4ever Music UA",
        "Fresh Concerts",
        "Disco Polo Music PL",
        "MTV 00s",
        "Bridge TV",
        "Sky High Concert HD",
        "MTV MUSIC IL",
        "music",
        "Clubbing TV HD",
        "Europa Plus TV orig",
        "MTV Viihde HD FI",
        "Backus TV Music HD",
        "Music Box Russia HD",
        "MTV Hits [UK]",
        "VOX MUSIC TV [PL]",
        "Club MTV",
        "MTV ישראל",
        "4ever Music HD UA",
        "מוזיקה 24",
        "Bridge Deluxe HD",
        "Europa Plus TV",
        "B4U Music IN",
        "IL: MTV HD",
        "Bridge Deluxe HD orig",
        "BOX Music 4K HDR",
        "Retro Music TV HD CZ",
        "מיוזיק 24",
        "Music Box Russia",
        "EU Music UA",
        "Stingray Hit List HD",
        "Classic Music HD",
        "KLI Music HD",
        "Bridge Hits",
        "Vox Music TV PL",
        "MTV 00's PT",
        "EU Music HD UA",
        "Fresh Dance",
        "Now 80s HD UK",
        "ТНТ Music",
        "music 24",
        "Z!Music HD",
        "Clarity4K Korean music",
        "MTV 00s RO",
        "MusicBox GE",
        "ערוץ 24",
        "C Music TV",
        "MTV Classic",
        "ITV 2 [UK]",
        "Music Channel [IL]",
        "Bridge TV ROCK",
        "MTV Hits [RO]",
        "Stingray Pop Adult HD",
        "Music Box Gold",
        "MTV RO",
        "BRIDGE TV Deluxe",
        "IL: VH1",
        "Clarity4K Latin music",
        "Yosso TV Music Hits",
        "IT: MTV HD",
        "Bridge TV Classic",
        "Biz Music HD UZ",
        "Bridge Rock",
        "MTV Base HD",
        "MTV POLSKA [PL]",
        "MTV Hits RO",
        "MTV HD [DE]",
        "HIT MUSIC [RO]",
        "MTV 90s",
        "VF Music",
        "Sochi Music HD",
        "מוסיקה",
        "MTV Classic USA",
        "IL: VH1 Classic",
        "Now 90s HD UK",
        "SUN Music IN",
        "NOW 70s UK",
        "MTV Base UK",
        "Rock Classics",
        "Stingray Hot Country HD",
        "MTV Pulse HD",
        "Stingray",
        "VB MTV Old Россия HD",
        "Public Music IN",
        "MTV Viihde HD SE",
        "Clarity4K Bollywood music",
        "Music Channel RO",
        "וי אייץ 1",
        "FRESH Sad Music HD",
        "Prokop TV Music",
        "ТНТ Music HD",
        "MTV HD CA",
        "MTV SE",
        "Clarity4K Remastered music",
        "MTV India IN",
        "IL: Music IL FHD",
        "MTV Music UK",
        "MTV Idol HD",
        "Classic Music",
        "Europa Plus TV HD",
        "MTV Aitio HD SE",
        "BRIDGE TV HITS",
        "MUSIC",
        "MTV Hits",
        "IL: Music IL HD",
        "ТНТ Music orig",
        "MTV HD [UK]",
        "MTV Club",
        "BRIDGE TV Русский Хит",
        "IL: MTV Hits",
        "MUSIC 24",
        "MTV Live HD",
        "Clarity4K Russian music",
        "IL: MTV Isreal",
        "MTV Dance [RO]",
        "MUSIC 24 IL",
        "Music Box Russia orig"
    ],
    "Nature🌴": [
        "נשיונל גאוגרפיק",
        "איי די",
        "ZEE TV [IL]",
        "NATIONAL GEOGRAPHICS HD IL",
        "IL: Travel Channel",
        "History [IL]",
        "TRAVEL CHANNEL IL",
        "Nat Geo Wild",
        "IL: Animal Planet",
        "דיסקברי צאנל",
        "Sky Select 5 HD",
        "נט ג׳יו ויילד",
        "Travel Channel [IL]",
        "Animal Planet HD",
        "Discovery",
        "ערוץ ההיסטוריה",
        "נט ג׳יו",
        "National Geographic HD [IL]",
        "IL: Investigation Discovery",
        "NET GEO_WILD HD IL",
        "אנימל פלאנט",
        "טרוול צ׳אנל",
        "IL: Animal planet",
        "IETV [IL]",
        "Travel Channel",
        "ID",
        "ערוץ דיסקברי",
        "NAT GEO WILD IL",
        "National Geographic [IL]",
        "DISCOVERY CHANNEL HD IL",
        "Nat Geo HD",
        "National Geographic IL",
        "Animal Planet [IL]",
        "IL: Discovery HD",
        "Nat Geo Wild HD [IL]",
        "נשיונל גיאוגרפיק",
        "Discovery HD [IL]",
        "National Geographic HD IL",
        "אינבסטיגיישן דיסקברי"
    ],
    "World Series🌍": [
        "ויוה",
        "Yam Tihoni 2",
        "IL: Viva Telenovelas",
        "בוליווד",
        "IL: Turkish Dramas 2",
        "IL: Turkish Drama Plus",
        "Turkish Dramas Plus [IL]",
        "Mediterranean [IL]",
        "ים תיכוני",
        "Viva plus",
        "VIVA IL",
        "VIVA+ IL",
        "ויוה וינטג",
        "Turkish Dramas Plus IL",
        "Turkish Dramas Plus FHD IL",
        "סדרות הודיות",
        "IL: Free Movies 10 Stars HD",
        "מדיטרניאן",
        "The Mediterranean+ HD [IL]",
        "Vamos HD",
        "Viva Vintage",
        "Yam Tichoni IL",
        "Bollywood [IL]",
        "Viva+ IL",
        "Viva+",
        "Yamtihoni IL",
        "Turkish Dramas 2 HD IL",
        "Turkish Dramas 3 FHD IL",
        "BOLLYWOOD HD IL",
        "IL: Turkish Drama 3",
        "Yam Tichoni HD IL",
        "Yam Tihoni Plus",
        "IL: Spanish Drama Channel 2 HD",
        "IL: Bollywood Cinema India FHD",
        "סדרות טורקיות",
        "The Mediterranean [IL]",
        "Turkish Dramas 2 [IL]",
        "Aruch Sdarot Hahodiot",
        "ויוה פלוס",
        "Turkish Dramas Plus HD IL",
        "BOLLYSHOW HD IL",
        "Turkish Dramas 3 HD [IL]",
        "טלנובלות",
        "IL: VIVA",
        "IL: Bollywood HD",
        "IL: VIVA Plus",
        "סדרות ספרדיות",
        "Bollywood HD",
        "Star channel [IL]",
        "Viva Premium HD IL",
        "IL: Bollywood Serial FHD",
        "The Mediterranean HD [IL]",
        "IL: Spanish Drama Channel 1 HD",
        "Viva Premium HD [IL]",
        "IL: Turkish Drama 2",
        "VIVA HD IL",
        "Yam Tichoni+ HD IL",
        "Turkish Dramas Plus HD [IL]",
        "IL: Turkish Dramas FHD",
        "Bollywood HD [IL]",
        "Turkish Dramas 2 FHD IL",
        "IL: Turkish Drama HD",
        "Viva Plus [IL]",
        "Viva [IL]",
        "Viva",
        "Yam Tihoni 25",
        "ויוה פרימיום",
        "IL: Viva Istanbul FHD",
        "לטינו",
        "Turkish Dramas 2 HD [IL]",
        "Viva Vintage [IL]",
        "Yam Tihoni HD",
        "Turkish Dramas 3 HD IL"
    ],
    "Sting🐝": [
        "Sting TV",
        "Yes Sting",
        "StingTV",
        "Sting Movies",
        "STING",
        "סטינג TV",
        "Sting",
        "Sting Kids",
        "Sting Comedy",
        "סטינג",
        "Sting Action",
        "Yes STING",
        "יס סטינג",
        "סטינג טלוויזיה",
        "Sting Drama",
        "סטינג טיוי"
    ],
    "Next➡️": [
        "Next Kids",
        "Next",
        "נקסט",
        "YES Next",
        "Next TV",
        "Yes Next",
        "Next Action",
        "NextTV",
        "Next Drama",
        "Next Comedy",
        "נקסט טיוי",
        "נקסט TV",
        "Next Movies",
        "נקסט טלוויזיה",
        "NEXT",
        "יס נקסט"
    ],
    "Series": [
        "HOT3",
        "Yes TV Comedy",
        "Viva",
        "HOT בידור",
        "Yes TV Action",
        "Yes TV Drama",
        "סדרות",
        "דרמה",
        "מיני סדרה",
        "פרק",
        "עונה",
        "קומדיה"
    ],
    "Reality": [
        "דה מסיכה",
        "הכוכב הבא",
        "נינגה ישראל",
        "דה סטאר",
        "האח הגדול",
        "ריאליטי",
        "Love Island",
        "מאסטר שף",
        "דה ווייס"
    ],
    "Lifestyle": [
        "בית ועיצוב",
        "Food Time",
        "Food Network Россия",
        "טיפוח",
        "Travel+Adventure HD",
        "TVN Style PL",
        "Home Plus",
        "Fashion TV",
        "אוכל ובישול",
        "טיולים",
        "Good Life",
        "Food Network HD",
        "ערוץ האוכל",
        "Food Network PL",
        "פודי",
        "לייף סטייל"
    ],
    "Science": [
        "Animal Planet",
        "ניסוי",
        "טבע",
        "Nat Geo Wild",
        "חקר",
        "Discovery",
        "היסטוריה",
        "דוקומנטרי",
        "מדע",
        "National Geographic"
    ],
    "Religion": [
        "שידורי מורשת",
        "קבלה",
        "יהדות",
        "תורה",
        "Kabbalah TV",
        "Hidabroot"
    ],
    "Business": [
        "כלכלה",
        "עסקים",
        "Fox Business",
        "שוק ההון",
        "בורסה"
    ],
    "Tech": [
        "AI",
        "חדשנות",
        "Startup",
        "גאדגטים",
        "טכנולוגיה",
        "Tech"
    ],
    "Cooking": [
        "Food Network",
        "מטבח",
        "מתכונים",
        "ערוץ האוכל",
        "בישול",
        "Foody"
    ],
    "Travel": [
        "מסעות",
        "תיירות",
        "Travel Channel",
        "ערוץ הטיולים",
        "טיולים"
    ],
    "Health": [
        "Health Channel",
        "כושר",
        "ערוץ הבריאות",
        "בריאות",
        "רפואה"
    ],
    "Education": [
        "ערוץ חינוכית",
        "Eroluxe Schoolgirl",
        "Da Vinci Learning",
        "לימוד",
        "חינוך",
        "אוניברסיטה",
        "קמפוס",
        "כאן חינוכית"
    ],
    "Gaming": [
        "Esports",
        "גיימינג",
        "אי ספורט",
        "Twitch",
        "Gaming"
    ],
    "Anime": [
        "Anime",
        "מאנגה",
        "אנימה"
    ],
    "Radio": [
        "Star Family LV",
        "Eroluxe Creampie",
        "Amedia 1 HD",
        "SKY HIGH Scream",
        "Magic Family",
        "FM",
        "Eroluxe Step Family",
        "Star Family HD",
        "Amedia 2 HD",
        "Webradio",
        "Fresh Family",
        "Active Family PL",
        "רדיו",
        "AM",
        "Amedia Hit HD",
        "Amedia Premium HD",
        "Polsat Games",
        "JimJam",
        "Radio"
    ],
    "24/7": [
        "ללא הפסקה",
        "Non Stop",
        "24/7",
        "שידור רציף",
        "24x7"
    ],
    "World Italian": [
        "AXN White PL",
        "Viju+ Megahit HD",
        "Hinuhit",
        "KBC-Гай Ritchie & Tarantino",
        "Init TV LT",
        "SKY HIGH spirit"
    ],
    "World Turkish": [
        "TV Extra LV",
        "Metro PL",
        "Kentron",
        "Kinoteatr",
        "TV8 HD TR",
        "InUltra",
        "13th Street HD",
        "Show HD TR",
        "SKY HIGH Strike VHS"
    ],
    "World Russian": [
        "SKY HIGH Gunrush",
        "TNT PL",
        "Eroluxe Brunette",
        "Rustavi 2",
        "Ru.TV"
    ],
    "World German": [
        "SKY HIGH Undead",
        "ProSieben Maxx HD",
        "ProSieben HD",
        "Delfi TV LT",
        "Eroluxe Cheerleader",
        "Eroluxe Blondes"
    ],
    "World Spanish": [
        "Eroluxe Shemales",
        "1+1 Україна(test)",
        "Spiegel Geschichte HD",
        "Penthouse Quickies",
        "Eroluxe Lesbians",
        "Tagesschau 24 HD",
        "Eroluxe Blondes",
        "SKY HIGH heroes",
        "Crime + Investigation PL",
        "Biznes 24 PL",
        "Eroluxe Japanese",
        "ICTV 2(test)",
        "SKY HIGH fresh HD",
        "SKY HIGH fresh 60",
        "Fresh Premiere",
        "Fresh Rating",
        "Fresh VHS",
        "Fresh Fantastic",
        "Fresh Adventure",
        "Fresh Romantic",
        "Fresh Soviet",
        "Fresh TV Armenia"
    ],
    "World Persian": [
        "SKY HIGH spirit",
        "Gulli Girl"
    ],
    "World French": [
        "Fresh Romantic",
        "Fresh Rating",
        "Fresh Soviet",
        "SKY HIGH fresh HD",
        "SKY HIGH fresh 60",
        "Fresh TV Armenia",
        "Fresh VHS",
        "Fresh Fantastic",
        "Fresh Adventure",
        "Fresh Premiere"
    ],
    "Entertainment": [
        "TLC HD",
        "CBS Reality PL",
        "World Fashion Channel",
        "Fashion TV",
        "Polsat HD"
    ],
    "Nature": [
        "Travel Channel HD"
    ],
    "Sports": [
        "NHL Network HD"
    ],
    "News": [
        "VividRed HD",
        "Bridge Deluxe",
        "Bridge Фрэш",
        "Bridge TV Русский хит",
        "Bridge TV"
    ],
    "Music": [
        "Europa Plus TV"
    ],
    "World Series": [
        "Viva Plus",
        "VIVA TV",
        "Viva"
    ],
    "World Balkans": [
        "iConcerts"
    ],
    "World Chinese": [
        "Phoenix HD"
    ],
    "Kids": [
        "Zoom TV PL",
        "Polsat Jim Jam"
    ],
    "World Portuguese": [
        "TVP Kuptura PL"
    ]
}
